// CANVAS IMAGE
export const GET_CANVAS_IMAGES_LOADING = 'GET_CANVAS_IMAGES_LOADING';
export const GET_CANVAS_IMAGES_SUCCESS = 'GET_CANVAS_IMAGES_SUCCESS';
export const GET_CANVAS_IMAGES_FAIL = 'GET_CANVAS_IMAGES_FAIL';

export const GET_CANVAS_IMAGE_LOADING = 'GET_CANVAS_IMAGE_LOADING';
export const GET_CANVAS_IMAGE_SUCCESS = 'GET_CANVAS_IMAGE_SUCCESS';
export const GET_CANVAS_IMAGE_FAIL = 'GET_CANVAS_IMAGE_FAIL';

export const ADD_CANVAS_IMAGE_LOADING = 'ADD_CANVAS_IMAGE_LOADING';
export const ADD_CANVAS_IMAGE_SUCCESS = 'ADD_CANVAS_IMAGE_SUCCESS';
export const ADD_CANVAS_IMAGE_FAIL = 'ADD_CANVAS_IMAGE_FAIL';

export const EDIT_CANVAS_IMAGE_LOADING = 'EDIT_CANVAS_IMAGE_LOADING';
export const EDIT_CANVAS_IMAGE_SUCCESS = 'EDIT_CANVAS_IMAGE_SUCCESS';
export const EDIT_CANVAS_IMAGE_FAIL = 'EDIT_CANVAS_IMAGE_FAIL';

export const DELETE_CANVAS_IMAGE_LOADING = 'DELETE_CANVAS_IMAGE_LOADING';
export const DELETE_CANVAS_IMAGE_SUCCESS = 'DELETE_CANVAS_IMAGE_SUCCESS';
export const DELETE_CANVAS_IMAGE_FAIL = 'DELETE_CANVAS_IMAGE_FAIL';


/// CODRAWINGS

export const UNDO_CODRAWING_CHANGE_SUCCESS = 'UNDO_CODRAWING_CHANGE_SUCCES'
export const UNDO_CODRAWING_CHANGE_FAIL = 'UNDO_CODRAWING_CHANGE_FAIL'

export const ON_CODRAWING_STROKE = 'ON_CODRAWING_STROKE'
export const ON_CODRAWING_SUBSCRIBED = 'ON_CODRAWING_SUBSCRIBED'
export const ON_CODRAWING_UNDO = 'ON_CODRAWING_UNDO';
export const ON_CODRAWING_STROKE_ACKNOWLEDGED = 'ON_CODRAWING_STROKE_ACKNOWLEDGED'
export const ON_CODRAWING_INITIALIZE = 'ON_CODRAWING_INITIALIZE'
export const ON_CODRAWING_IMAGE_UPDATE = 'ON_CODRAWING_IMAGE_UPDATE'

export const CODRAWING_STROKE_FAILED = 'CODRAWING_STROKE_FAILED'
export const CODRAWING_UNDO_LOADING = 'CODRAWING_UNDO_LOADING';
export const CODRAWING_UNDO_SUCCESS = 'CODRAWING_UNDO_SUCCESS';
export const CODRAWING_UNDO_FAIL = 'CODRAWING_UNDO_FAIL';

export const SUBSCRIBE_CODRAWING_LOADING = 'SUBSCRIBE_CODRAWING_LOADING'
export const SUBSCRIBE_CODRAWING_SUCCESS = 'SUBSCRIBE_CODRAWING_SUCCES'
export const SUBSCRIBE_CODRAWING_FAIL = 'SUBSCRIBE_CODRAWING_FAIL'
export const UNSUBSCRIBE_CODRAWING_SUCCESS = 'UNSUBSCRIBE_CODRAWING_SUCCES'
export const UNSUBSCRIBE_CODRAWING_FAIL = 'UNSUBSCRIBE_CODRAWING_FAIL'




export const MARK_CANVAS_IMAGE_STROKES_PENDING = 'MARK_CANVAS_IMAGE_STROKES_PENDING';
export const MARK_CANVAS_IMAGE_UNSAVED = 'MARK_CANVAS_IMAGE_UNSAVED';
export const SAVE_CANVAS_IMAGE_LOADING = 'SAVE_CANVAS_IMAGE_LOADING';
export const SAVE_CANVAS_IMAGE_SUCCESS = 'SAVE_CANVAS_IMAGE_SUCCESS';
export const SAVE_CANVAS_IMAGE_FAIL = 'SAVE_CANVAS_IMAGE_FAIL';