
// TICKETING

export const GET_TICKETED_EVENTS_LOADING = 'GET_TICKETED_EVENTS_LOADING';
export const GET_TICKETED_EVENTS_SUCCESS = 'GET_TICKETED_EVENTS_SUCCESS';
export const GET_TICKETED_EVENTS_FAIL = 'GET_TICKETED_EVENTS_FAIL';

export const GET_TICKETED_EVENT_LOADING = 'GET_TICKETED_EVENT_LOADING';
export const GET_TICKETED_EVENT_SUCCESS = 'GET_TICKETED_EVENT_SUCCESS';
export const GET_TICKETED_EVENT_FAIL = 'GET_TICKETED_EVENT_FAIL';

export const ADD_TICKETED_EVENT_LOADING = 'ADD_TICKETED_EVENT_LOADING';
export const ADD_TICKETED_EVENT_SUCCESS = 'ADD_TICKETED_EVENT_SUCCESS';
export const ADD_TICKETED_EVENT_FAIL = 'ADD_TICKETED_EVENT_FAIL';

export const EDIT_TICKETED_EVENT_LOADING = 'EDIT_TICKETED_EVENT_LOADING';
export const EDIT_TICKETED_EVENT_SUCCESS = 'EDIT_TICKETED_EVENT_SUCCESS';
export const EDIT_TICKETED_EVENT_FAIL = 'EDIT_TICKETED_EVENT_FAIL';

export const DELETE_TICKETED_EVENT_LOADING = 'DELETE_TICKETED_EVENT_LOADING';
export const DELETE_TICKETED_EVENT_SUCCESS = 'DELETE_TICKETED_EVENT_SUCCESS';
export const DELETE_TICKETED_EVENT_FAIL = 'DELETE_TICKETED_EVENT_FAIL';


/// TICKET PURCHASES
export const UPDATE_TICKET_CART = 'UPDATE_TICKET_CART';
export const CLEAR_TICKET_CART = 'CLEAR_TICKET_CART';

// export const GET_TICKET_PURCHASES_LOADING = 'GET_TICKET_PURCHASES_LOADING';
// export const GET_TICKET_PURCHASES_SUCCESS = 'GET_TICKET_PURCHASES_SUCCESS';
// export const GET_TICKET_PURCHASES_FAIL = 'GET_TICKET_PURCHASES_FAIL';

export const GET_TICKET_PURCHASES_BY_EVENT_LOADING = 'GET_TICKET_PURCHASES_BY_EVENT_LOADING';
export const GET_TICKET_PURCHASES_BY_EVENT_SUCCESS = 'GET_TICKET_PURCHASES_BY_EVENT_SUCCESS';
export const GET_TICKET_PURCHASES_BY_EVENT_FAIL = 'GET_TICKET_PURCHASES_BY_EVENT_FAIL';

// export const GET_TICKET_PURCHASE_LOADING = 'GET_TICKET_PURCHASE_LOADING';
// export const GET_TICKET_PURCHASE_SUCCESS = 'GET_TICKET_PURCHASE_SUCCESS';
// export const GET_TICKET_PURCHASE_FAIL = 'GET_TICKET_PURCHASE_FAIL';

// export const ADD_TICKET_PURCHASE_LOADING = 'ADD_TICKET_PURCHASE_LOADING';
// export const ADD_TICKET_PURCHASE_SUCCESS = 'ADD_TICKET_PURCHASE_SUCCESS';
// export const ADD_TICKET_PURCHASE_FAIL = 'ADD_TICKET_PURCHASE_FAIL';

// export const EDIT_TICKET_PURCHASE_LOADING = 'EDIT_TICKET_PURCHASE_LOADING';
// export const EDIT_TICKET_PURCHASE_SUCCESS = 'EDIT_TICKET_PURCHASE_SUCCESS';
// export const EDIT_TICKET_PURCHASE_FAIL = 'EDIT_TICKET_PURCHASE_FAIL';

// export const DELETE_TICKET_PURCHASE_LOADING = 'DELETE_TICKET_PURCHASE_LOADING';
// export const DELETE_TICKET_PURCHASE_SUCCESS = 'DELETE_TICKET_PURCHASE_SUCCESS';
// export const DELETE_TICKET_PURCHASE_FAIL = 'DELETE_TICKET_PURCHASE_FAIL';