/////////////////////////////////////
/////////////////////////////////////
import store from "../../../store"
import { ON_TOUCH_ACTIVE } from "./event"

// EFFECTS
export const EFFECT_TELEPORT = 'EFFECT_TELEPORT'
export const EFFECT_FOLLOW_START = 'EFFECT_FOLLOW_START'
export const EFFECT_FOLLOW_END = 'EFFECT_FOLLOW_END'

export const EFFECT_IGNORE_GRAVITY = 'EFFECT_IGNORE_GRAVITY'
export const EFFECT_STICK_TO = 'EFFECT_STICK_TO'

export const EFFECT_TRANSFORM = 'EFFECT_TRANSFORM'
export const EFFECT_SPAWN = 'EFFECT_SPAWN'
export const EFFECT_DESTROY = 'EFFECT_DESTROY'

export const EFFECT_CUTSCENE = 'EFFECT_CUTSCENE'
export const EFFECT_SWITCH_STAGE = 'EFFECT_SWITCH_STAGE'

export const EFFECT_CAMERA_SHAKE = 'EFFECT_CAMERA_SHAKE'
export const EFFECT_INVISIBLE = 'EFFECT_INVISIBLE'

export const EFFECT_GAME_OVER = 'EFFECT_GAME_OVER'
export const EFFECT_WIN_GAME = 'EFFECT_WIN_GAME'

export const EFFECT_OPEN_OVERLAY = 'EFFECT_OPEN_OVERLAY'
export const EFFECT_CHANGE_GAME = 'EFFECT_CHANGE_GAME'

export const NO_RELATION_TAG_EFFECT = 'NO_RELATION_TAG_EFFECT'
export const SINGLE_RELATION_TAG_EFFECT = 'SINGLE_RELATION_TAG_EFFECT'
export const TWO_RELATION_TAG_EFFECT = 'TWO_RELATION_TAG_EFFECT'

// WHAT HAPPENS
export const defaultEffect = {
  effectBehavior: '',
  effectId: null,

  remoteEffectedRelationTagIds: [],

  stageId: null,
  spawnEntityClassId: null,
  entityClassId: null,
  arcadeGameMongoId: null,
  zoneEntityClassId: null,
  cutsceneId: null,
  text: '',
  
  isAutogenerated: false,
  isRemoved: false,

  customSelectorCategory: null
}

export const SPAWN_ZONE_A_SELECT = 'SPAWN_ZONE_A_SELECT';
export const SPAWN_ZONE_B_SELECT = 'SPAWN_ZONE_B_SELECT';
export const SPAWN_ZONE_RANDOM_SELECT = 'SPAWN_ZONE_RANDOM_SELECT';

export const spawnZoneSelectorTypeToDisplayName = {
  [SPAWN_ZONE_A_SELECT]: 'Spawn in Tag A Instance',
  [SPAWN_ZONE_B_SELECT]: 'Spawn in Tag B Instance',
  [SPAWN_ZONE_RANDOM_SELECT]: 'Spawn in Random Instance of Zone',
}

export const effectBehaviorToDisplayNames = {
  // Movement
  [EFFECT_TELEPORT]: 'Teleport',
  [EFFECT_IGNORE_GRAVITY]: 'Remove gravity',
  [EFFECT_STICK_TO]: 'Hold',

  // Lifecycle
  [EFFECT_TRANSFORM]: 'Transform',
  [EFFECT_SPAWN]: 'Spawn',
  [EFFECT_DESTROY]: 'Destroy',

  // Narrative
  [EFFECT_CUTSCENE]: 'Play Dialog/Cutscene',
  [EFFECT_GAME_OVER]: 'Game Over',
  [EFFECT_WIN_GAME]: 'Win Game',

  // Graphical
  [EFFECT_CAMERA_SHAKE]: 'Shake Camera',
  [EFFECT_INVISIBLE]: 'Hide',

  // Meta
  [EFFECT_OPEN_OVERLAY]: 'Send to Stars',
  [EFFECT_CHANGE_GAME]: 'Change Game',
  [EFFECT_SWITCH_STAGE]: 'Switch Stage',
}

/////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////
//// EFFECT
export const effectBehaviorInterfaces = {
  // Movement
  [EFFECT_TELEPORT]: {
    zoneEntityClassId: 'Teleport to which zone?',
    effectableType: TWO_RELATION_TAG_EFFECT,
  },
  [EFFECT_IGNORE_GRAVITY]: {
    effectableType: TWO_RELATION_TAG_EFFECT,
    isStandalone: true
  },
  [EFFECT_STICK_TO]: {
    effectableType: SINGLE_RELATION_TAG_EFFECT,
    isStandalone: true
  },

  // Lifecycle
  [EFFECT_TRANSFORM]: {
    entityClassId: 'Transform into which object?',
    effectableType: TWO_RELATION_TAG_EFFECT,
  },
  [EFFECT_SPAWN]: {
    zoneEntityClassId: 'Spawn in which Zone?',
    effectCooldown: true,
    spawnEntityClassId: 'Which Class will be spawned?',
    spawnZoneSelectorType: true,  
    effectableType: NO_RELATION_TAG_EFFECT,
    isCustomizeable: true,
  },
  [EFFECT_DESTROY]: {
    effectableType: TWO_RELATION_TAG_EFFECT,
    isStandalone: true
  },

  // Narrative
  [EFFECT_CUTSCENE]: {
    cutsceneId: 'Which cutscene?',
    effectableType: NO_RELATION_TAG_EFFECT
  },
  [EFFECT_GAME_OVER]: {
    text: 'Message',
    effectableType: NO_RELATION_TAG_EFFECT,
    isCustomizeable: true
  },
  [EFFECT_WIN_GAME]: {
    text: 'Message',
    effectableType: NO_RELATION_TAG_EFFECT,
    isCustomizeable: true
  },

  // Graphical
  [EFFECT_CAMERA_SHAKE]: {
    // number: 'How intense is the camera shake?',
    // effectCooldown: true,
    effectableType: NO_RELATION_TAG_EFFECT,
    isStandalone: true
  },
  [EFFECT_INVISIBLE]: {
    effectableType: TWO_RELATION_TAG_EFFECT,
    isStandalone: true
  },

  // Meta
  [EFFECT_SWITCH_STAGE]: {
    stageId: 'Which stage?',
    // zoneEntityClassId: 'Spawn in which Zone?',
    // entityClassId: 'Transform into which object? (Optional)',
    effectableType: NO_RELATION_TAG_EFFECT,
    isCustomizeable: true
  },
  [EFFECT_CHANGE_GAME]: {
    arcadeGameMongoId: 'Which game?',
    effectableType: NO_RELATION_TAG_EFFECT,
    isCustomizeable: true
  },
  [EFFECT_OPEN_OVERLAY]: {
    effectableType: NO_RELATION_TAG_EFFECT,
    isStandalone: true
  },
}

// EFFECT_CAMERA_SHAKE, EFFECT_WIN_GAME, EFFECT_GAME_OVER, EFFECT_DESTROY, EFFECT_DESTROY, EFFECT_TRANSFORM, EFFECT_SPAWN, EFFECT_CUTSCENE
export const persistentEffects  = {
  // Movement
  [EFFECT_TELEPORT]: false,
  [EFFECT_IGNORE_GRAVITY]: true,
  [EFFECT_STICK_TO]: true,

  // Lifecycle
  [EFFECT_TRANSFORM]: false,
  [EFFECT_SPAWN]: false,
  [EFFECT_DESTROY]: false,

  // Narrative
  [EFFECT_CUTSCENE]: false,
  [EFFECT_GAME_OVER]: false,
  [EFFECT_WIN_GAME]: false,

  // Graphical
  [EFFECT_CAMERA_SHAKE]: false,
  [EFFECT_INVISIBLE]: true,

  // Meta
  [EFFECT_SWITCH_STAGE]: false,
  [EFFECT_CHANGE_GAME]: false,
  [EFFECT_OPEN_OVERLAY]: false
}

export const nonRemoteEffects  = {
  // Movement
  [EFFECT_TELEPORT]: false,
  [EFFECT_IGNORE_GRAVITY]: false,
  [EFFECT_STICK_TO]: true,

  // Lifecycle
  [EFFECT_TRANSFORM]: false,
  [EFFECT_SPAWN]: true,
  [EFFECT_DESTROY]: false,

  // Narrative
  [EFFECT_CUTSCENE]: true,
  [EFFECT_GAME_OVER]: true,
  [EFFECT_WIN_GAME]: true,

  // Graphical
  [EFFECT_CAMERA_SHAKE]: true,
  [EFFECT_INVISIBLE]: false,

  [EFFECT_SWITCH_STAGE]: true,
  [EFFECT_CHANGE_GAME]: true,
  [EFFECT_OPEN_OVERLAY]: true
}

export function isUseableEffect(effectBehavior, eventType) {
  if(eventType !== ON_TOUCH_ACTIVE && persistentEffects[effectBehavior]) return false
  if(!persistentEffects[effectBehavior] && (eventType === ON_TOUCH_ACTIVE)) return false
  return true
}

export function getEffectShorthand(effect) {
  const effectBehavior = effect.effectBehavior 
  const displayName = effectBehaviorToDisplayNames[effectBehavior]
  const gameModel = store.getState().gameModel.gameModel
  const entityClasses = gameModel.entityClasses 
  const cutscenes = gameModel.cutscenes 
  const relationTags = gameModel.relationTags 

  if(effectBehavior === EFFECT_TELEPORT) {
    return displayName + ` to  ${entityClasses[effect.zoneEntityClassId].name}` 
  }

  if(effectBehavior === EFFECT_TRANSFORM) {
    return displayName + ` into  ${entityClasses[effect.entityClassId].name}`
  }

  if(effectBehavior === EFFECT_SPAWN) {
    return displayName + ` ${entityClasses[effect.spawnEntityClassId].name}  into  ${entityClasses[effect.zoneEntityClassId].name}`
  }

  if(effectBehavior === EFFECT_CUTSCENE) {
    return displayName + `  ${cutscenes[effect.cutsceneId].name}`
  }

  if(effectBehavior === EFFECT_DESTROY) {
    if(effect.remoteEffectedRelationTagIds?.length) {
      const relationTagNames = effect.remoteEffectedRelationTagIds.map((relationTagId) => relationTags[relationTagId].name)
      return displayName + ` all ${relationTagNames}`
    }
  }

  return displayName
}