
import { BASIC_CLASS, BASIC_CLASS_TYPE_PREFIX, NPC_CLASS, NPC_CLASS_TYPE_PREFIX, PLAYER_CLASS, PLAYER_CLASS_TYPE_PREFIX, POWERUP_CLASS, POWERUP_CLASS_TYPE_PREFIX, ZONE_CLASS, ZONE_CLASS_TYPE_PREFIX } from "..";

export const classTypeToPrefix = {
  [ZONE_CLASS]: ZONE_CLASS_TYPE_PREFIX,
  [PLAYER_CLASS]: PLAYER_CLASS_TYPE_PREFIX,
  [BASIC_CLASS]: BASIC_CLASS_TYPE_PREFIX,
  [NPC_CLASS]: NPC_CLASS_TYPE_PREFIX,
  [POWERUP_CLASS]: POWERUP_CLASS_TYPE_PREFIX
}

export const classTypeToDisplayName = {
  [PLAYER_CLASS]: 'Player',
  [BASIC_CLASS]: 'Object',
  [ZONE_CLASS]: 'Zone',
  [NPC_CLASS]: 'NPC',
  [POWERUP_CLASS]: 'Powerup',
}
  



  

  
  