export const ON_SOCKET_CONNECT = 'ON_SOCKET_CONNECT';
export const ON_SOCKET_DISCONNECT = 'ON_SOCKET_DISCONNECT';

export const ON_AUTHENTICATE_SOCKET_SUCCESS = 'ON_AUTHENTICATE_SOCKET_SUCCESS';
export const ON_AUTHENTICATE_SOCKET_FAIL = 'ON_AUTHENTICATE_SOCKET_FAIL';

export const ON_GAME_INSTANCE_UPDATE = 'ON_GAME_INSTANCE_UPDATE';
export const ON_GAME_MODEL_UPDATE = 'ON_GAME_MODEL_UPDATE';

export const ON_LOBBY_UPDATE = 'ON_LOBBY_UPDATE';
export const ON_LOBBY_USER_STATUS_UPDATE = 'ON_LOBBY_USER_STATUS_UPDATE';
export const ON_COBROWSING_UPDATE = 'ON_COBROWSING_UPDATE';
export const ON_COBROWSING_STATUS_UPDATE = 'ON_COBROWSING_STATUS_UPDATE';
export const ON_COBROWSING_SUBSCRIBED = 'ON_COBROWSING_SUBSCRIBED';
export const ON_COBROWSING_REMOTE_DISPATCH = 'ON_COBROWSING_REMOTE_DISPATCH';

export const ON_CODRAWING_STROKE = 'ON_CODRAWING_STROKE'
export const ON_CODRAWING_SUBSCRIBED = 'ON_CODRAWING_SUBSCRIBED'