export const EDIT_GAME_SCOPE_EXPERIENCE_INSTANCE = 'EDIT_GAME_SCOPE_EXPERIENCE_INSTANCE';
export const EDIT_GAME_SCOPE_ONLY_ME = 'EDIT_GAME_SCOPE_ONLY_ME';
export const EDIT_GAME_SCOPE_USER_LIST = 'EDIT_GAME_SCOPE_USER_LIST';
export const EDIT_GAME_SCOPE_ANYONE = 'EDIT_GAME_SCOPE_ANYONE';