
export const SOCKET_SESSIONS_STORE = 'SOCKET_SESSIONS_STORE'
export const GAME_ROOMS_STORE = 'GAME_ROOMS_STORE'
export const LOBBY_INSTANCE_STORE = 'LOBBY_INSTANCE_STORE'
export const SOCKET_IO_STORE = 'SOCKET_IO_STORE'