export const OPEN_GAME_METADATA_AID = 'OPEN_GAME_METADATA_AID';
export const OPEN_SPRITE_EDITOR_AID = 'OPEN_SPRITE_EDITOR_AID';
export const OPEN_EDIT_ENTITY_GRAPHICS_AID = 'OPEN_EDIT_ENTITY_GRAPHICS_AID';
export const OPEN_STAGE_BOUNDARIES_EDITOR_AID = 'OPEN_STAGE_BOUNDARIES_EDITOR_AID';
export const OPEN_CURRENT_STAGE_EDITOR_AID = 'OPEN_CURRENT_STAGE_EDITOR_AID';
export const OPEN_GAME_SNAPSHOT_TAKER_AID = 'OPEN_GAME_SNAPSHOT_TAKER_AID';
export const OPEN_CREATE_ENTITY_AID = 'OPEN_CREATE_ENTITY_AID';
export const OPEN_EDIT_ENTITY_AID = 'OPEN_EDIT_ENTITY_AID';