export const ACTIVITY_DID = 'activity-'

export const GAME_ROOM_ACTIVITY = 'GAME_ROOM_ACTIVITY'
export const WAITING_ROOM = 'WAITING_ROOM'
export const CHATROOM_ACTIVITY = 'CHATROOM_ACTIVITY'
export const CREDITS_ACTIVITY = 'CREDITS_ACTIVITY'
export const SERVICE_ACTIVITY = 'SERVICE_ACTIVITY'
export const VIDEO_ACTIVITY = 'VIDEO_ACTIVITY'
export const DRAWING_ACTIVITY = 'DRAWING_ACTIVITY'