
export const EXPERIENCE_PRESET_CONVEYER_BELT = 'EXPERIENCE_PRESET_CONVEYER_BELT';
export const EXPERIENCE_PRESET_CREATE_GAME = 'EXPERIENCE_PRESET_CREATE_GAME';
export const EXPERIENCE_PRESET_CONVERGING_TRACKS = 'EXPERIENCE_PRESET_CONVERGING_TRACKS';
export const EXPERIENCE_PRESET_BATTLE_ROYALE = 'EXPERIENCE_PRESET_BATTLE_ROYALE';
export const EXPERIENCE_PRESET_ADVENTURE_GAME = 'EXPERIENCE_PRESET_ADVENTURE_GAME';

export const SINGLE_LOBBY_EXPERIENCE = 'SINGLE_LOBBY_EXPERIENCE';
export const MULTI_LOBBY_EXPERIENCE = 'MULTI_LOBBY_EXPERIENCE';
export const DYNAMIC_LOBBY_EXPERIENCE = 'DYNAMIC_LOBBY_EXPERIENCE';
