export const EXPERIENCE_EFFECT_DID = 'ee-'

export const EXPERIENCE_EFFECT_GAME_EFFECT = 'EXPERIENCE_EFFECT_GAME_EFFECT';

export const EXPERIENCE_EFFECT_CHANGE_ACTIVITY = 'EXPERIENCE_EFFECT_CHANGE_ACTIVITY';
export const EXPERIENCE_EFFECT_CHANGE_INSTRUCTION = 'EXPERIENCE_EFFECT_CHANGE_INSTRUCTION';
export const EXPERIENCE_EFFECT_CHANGE_LOBBY = 'EXPERIENCE_EFFECT_CHANGE_LOBBY';

export const EXPERIENCE_EFFECT_OPEN_TRANSITION = 'EXPERIENCE_EFFECT_OPEN_TRANSITION'
export const EXPERIENCE_EFFECT_CLOSE_TRANSITION = 'EXPERIENCE_EFFECT_CLOSE_TRANSITION'
export const EXPERIENCE_EFFECT_LEAVE_CONTROL_BOOTH = 'EXPERIENCE_EFFECT_LEAVE_CONTROL_BOOTH'
export const EXPERIENCE_EFFECT_GO_TO_CONTROL_BOOTH = 'EXPERIENCE_EFFECT_GO_TO_CONTROL_BOOTH'
export const EXPERIENCE_EFFECT_GO_TO_INSTRUCTION_STEP = 'EXPERIENCE_EFFECT_GO_TO_INSTRUCTION_STEP'
