export const INSTRUCTION_DRAWING_ROOM = 'INSTRUCTION_DRAWING_ROOM'
export const INSTRUCTION_GAME_ROOM = 'INSTRUCTION_GAME_ROOM'
export const INSTRUCTION_LOBBY = 'INSTRUCTION_LOBBY'
export const INSTRUCTION_DID = 'instruction-'