export const LOBBY_DID = 'lobby-'

export const defaultLobbyId = LOBBY_DID + 'default';

export const ROLE_SECURITY_SCOPE_PUBLIC = 'ROLE_SECURITY_SCOPE_PUBLIC'
export const ROLE_SECURITY_SCOPE_INVITE_ONLY = 'ROLE_SECURITY_SCOPE_INVITE_ONLY'
export const ROLE_SECURITY_SCOPE_UNLISTED = 'ROLE_SECURITY_SCOPE_UNLISTED'
