/// PORTFOLIO
export const PAUSE_BACKGROUND_MUSIC = 'PAUSE_BACKGROUND_MUSIC'
export const UNPAUSE_BACKGROUND_MUSIC = 'UNPAUSE_BACKGROUND_MUSIC'
export const PLAY_BACKGROUND_MUSIC = 'PLAY_BACKGROUND_MUSIC'
export const MUTE_VIDEO_AUDIO = 'MUTE_VIDEO_AUDIO'
export const UNMUTE_VIDEO_AUDIO = 'UNMUTE_VIDEO_AUDIO'
