import { BACKGROUND_CANVAS_ID, FOREGROUND_CANVAS_ID, PLAYGROUND_CANVAS_ID } from "../../game/constants";

export const BRUSH_SIZE_IID = 'brushSize';
export const ADD_BRUSH_IID = 'addBrush';

export const BACKGROUND_CANVAS_CONTAINER_IID = 'BACKGROUND_CANVAS/*';
export const BACKGROUND_CANVAS_ADD_BRUSH_IID = 'BACKGROUND_CANVAS/addBrush'
export const BACKGROUND_CANVAS_COLOR_SELECT_IID = 'BACKGROUND_CANVAS/colorSelect'
export const BACKGROUND_CANVAS_BRUSH_SELECT_IID = 'BACKGROUND_CANVAS/brushSelect'

export const PLAYGROUND_CANVAS_CONTAINER_IID = 'PLAYGROUND_CANVAS/*';
export const PLAYGROUND_CANVAS_ADD_BRUSH_IID = 'PLAYGROUND_CANVAS/addBrush'
export const PLAYGROUND_CANVAS_COLOR_SELECT_IID = 'PLAYGROUND_CANVAS/colorSelect'
export const PLAYGROUND_CANVAS_BRUSH_SELECT_IID = 'PLAYGROUND_CANVAS/brushSelect'

export const FOREGROUND_CANVAS_CONTAINER_IID = 'FOREGROUND_CANVAS/*';
export const FOREGROUND_CANVAS_ADD_BRUSH_IID = 'FOREGROUND_CANVAS/addBrush'
export const FOREGROUND_CANVAS_COLOR_SELECT_IID = 'FOREGROUND_CANVAS/colorSelect'
export const FOREGROUND_CANVAS_BRUSH_SELECT_IID = 'FOREGROUND_CANVAS/brushSelect'

export function getBrushSelectFromCanvasId(canvasId) {
  if(canvasId === BACKGROUND_CANVAS_ID) return BACKGROUND_CANVAS_BRUSH_SELECT_IID
  if(canvasId === FOREGROUND_CANVAS_ID) return FOREGROUND_CANVAS_BRUSH_SELECT_IID
  if(canvasId === PLAYGROUND_CANVAS_ID) return PLAYGROUND_CANVAS_BRUSH_SELECT_IID
}
export function getColorSelectFromCanvasId(canvasId) {
  if(canvasId === BACKGROUND_CANVAS_ID) return BACKGROUND_CANVAS_COLOR_SELECT_IID
  if(canvasId === FOREGROUND_CANVAS_ID) return FOREGROUND_CANVAS_COLOR_SELECT_IID
  if(canvasId === PLAYGROUND_CANVAS_ID) return PLAYGROUND_CANVAS_COLOR_SELECT_IID
}