import { BACKGROUND_LAYER_CANVAS_ID, FOREGROUND_LAYER_CANVAS_ID, PLAYGROUND_LAYER_CANVAS_ID } from "../../game/constants";

export const BRUSH_SIZE_IID = 'brushSize';
export const ADD_BRUSH_IID = 'addBrush';

export const BACKGROUND_LAYER_CANVAS_CONTAINER_IID = 'BACKGROUND_LAYER_CANVAS/*';
export const BACKGROUND_LAYER_CANVAS_ADD_BRUSH_IID = 'BACKGROUND_LAYER_CANVAS/addBrush'
export const BACKGROUND_LAYER_CANVAS_COLOR_SELECT_IID = 'BACKGROUND_LAYER_CANVAS/colorSelect'
export const BACKGROUND_LAYER_CANVAS_BRUSH_SELECT_IID = 'BACKGROUND_LAYER_CANVAS/brushSelect'

export const PLAYGROUND_LAYER_CANVAS_CONTAINER_IID = 'PLAYGROUND_LAYER_CANVAS/*';
export const PLAYGROUND_LAYER_CANVAS_ADD_BRUSH_IID = 'PLAYGROUND_LAYER_CANVAS/addBrush'
export const PLAYGROUND_LAYER_CANVAS_COLOR_SELECT_IID = 'PLAYGROUND_LAYER_CANVAS/colorSelect'
export const PLAYGROUND_LAYER_CANVAS_BRUSH_SELECT_IID = 'PLAYGROUND_LAYER_CANVAS/brushSelect'

export const FOREGROUND_LAYER_CANVAS_CONTAINER_IID = 'FOREGROUND_LAYER_CANVAS/*';
export const FOREGROUND_LAYER_CANVAS_ADD_BRUSH_IID = 'FOREGROUND_LAYER_CANVAS/addBrush'
export const FOREGROUND_LAYER_CANVAS_COLOR_SELECT_IID = 'FOREGROUND_LAYER_CANVAS/colorSelect'
export const FOREGROUND_LAYER_CANVAS_BRUSH_SELECT_IID = 'FOREGROUND_LAYER_CANVAS/brushSelect'

export function getBrushSelectFromLayerCanvasId(layerCanvasId) {
  if(layerCanvasId === BACKGROUND_LAYER_CANVAS_ID) return BACKGROUND_LAYER_CANVAS_BRUSH_SELECT_IID
  if(layerCanvasId === FOREGROUND_LAYER_CANVAS_ID) return FOREGROUND_LAYER_CANVAS_BRUSH_SELECT_IID
  if(layerCanvasId === PLAYGROUND_LAYER_CANVAS_ID) return PLAYGROUND_LAYER_CANVAS_BRUSH_SELECT_IID
}
export function getColorSelectFromLayerCanvasId(layerCanvasId) {
  if(layerCanvasId === BACKGROUND_LAYER_CANVAS_ID) return BACKGROUND_LAYER_CANVAS_COLOR_SELECT_IID
  if(layerCanvasId === FOREGROUND_LAYER_CANVAS_ID) return FOREGROUND_LAYER_CANVAS_COLOR_SELECT_IID
  if(layerCanvasId === PLAYGROUND_LAYER_CANVAS_ID) return PLAYGROUND_LAYER_CANVAS_COLOR_SELECT_IID
}