export const brushInterfaceIds = {
  "brushSize": {},
  "addBrush": {},
  "PLAYGROUND_CANVAS": {},
  "PLAYGROUND_CANVAS/*": {},
  "PLAYGROUND_CANVAS/addBrush": {},
  "PLAYGROUND_CANVAS/colorSelect": {},
  "PLAYGROUND_CANVAS/brushSelect": {},
  "FOREGROUND_CANVAS": {},
  "FOREGROUND_CANVAS/*": {},
  "FOREGROUND_CANVAS/addBrush": {},
  "FOREGROUND_CANVAS/colorSelect": {},
  "FOREGROUND_CANVAS/brushSelect": {},
  "BACKGROUND_CANVAS": {},
  "BACKGROUND_CANVAS/*": {},
  "BACKGROUND_CANVAS/addBrush": {},
  "BACKGROUND_CANVAS/colorSelect": {},
  "BACKGROUND_CANVAS/brushSelect": {},
}