export const COBROWSING_CLICK_IID = 'COBROWSING_CLICK_IID';
export const COBROWSING_UNLOCK_IID = 'COBROWSING_UNLOCK_IID';
export const COBROWSING_WIGGLE_IID = 'COBROWSING_WIGGLE_IID';
export const COBROWSING_ACTIVE_TOGGLE_IID = 'COBROWSING_ACTIVE_TOGGLE_IID';