export const contextMenuInterfaceIds = {
   "contextMenu": {},
  "contextMenu/*": {},
   "contextMenu/class": {},
  "contextMenu/class/jump": {},
  "contextMenu/class/graphics": {},
  "contextMenu/class/physics": {},
  "contextMenu/class/movement": {},
  "contextMenu/class/relations": {},
  "contextMenu/class/duplicate": {},
  "contextMenu/class/camera": {},
  "contextMenu/class/projectile": {},
  "contextMenu/stage": {},
  "contextMenu/stage/gravity": {},
  "contextMenu/stage/sections": {},
  "contextMenu/stage/backgroundColor": {},
  "contextMenu/metadata": {},
  "contextMenu/toggleGrid": {},
  "contextMenu/takeSnapshot": {},
  "contextMenu/cutscenes": {},
  "contextMenu/instance": {},
  "contextMenu/instance/resize": {},
  "contextMenu/instance/move": {}
}