export const DIALOGUE_ADD_IID = 'dialogue/add'
export const DIALOGUE_SELECT_IID = 'dialogue/select'
export const DIALOGUE_SHORTCUT_IID = 'dialogue/inShortcutMenu'
export const DIALOGUE_CONTAINER_IID = 'dialogue/*'
export const DIALOGUE_MORE_IID = 'dialogue/more'

export const CUTSCENE_ADD_IID = 'cutscene/add'
export const CUTSCENE_SELECT_IID = 'cutscene/select'
export const CUTSCENE_CONTAINER_IID = 'cutscene/*'
export const CUTSCENE_MORE_IID = 'cutscene/more'