
export const GAME_MODEL_IMPORT_IID = 'GAME_MODEL_IMPORT_IID'
export const REMOVED_DATA_SHOW_IID = 'showRemoved'
export const ENTITY_BOX_OPEN_IID = "selector/openEntityBox";

// NO DATA YET
export const DERIVED_AUTOGENERATION_IID = 'DERIVED_AUTOGENERATION_IID'
export const DERIVED_ENTITY_MODEL_IID = 'DERIVED_ENTITY_MODEL_IID'
export const DERIVED_DEFAULT_SYSTEM_IID = 'DERIVED_DEFAULT_SYSTEM_IID'
export const DERIVED_INTERFACE_ACTION_IID = 'DERIVED_INTERFACE_ACTION_IID'

export const NOT_DERIVED_IID = 'NOT_DERIVED_IID'

// --------------------------------------------