export const ENTITY_BOX_DIALOG_IID = "entity/box";
export const EDIT_ENTITY_GRAPHICS_PRIMARY_DIALOG_IID = 'EDIT_ENTITY_GRAPHICS_PRIMARY_DIALOG_IID'

export const CREATE_TEXTURE_CREATE_COLOR_DIALOG_IID = 'CREATE_TEXTURE_CREATE_COLOR_DIALOG_IID'
export const LAYER_CREATE_COLOR_DIALOG_IID = 'LAYER_CREATE_COLOR_DIALOG_IID'
export const AGREGGATE_CREATE_COLOR_DIALOG_IID = 'AGREGGATE_CREATE_COLOR_DIALOG_IID'

export const LAYER_AGGREGATE_COLOR_SELECT_IID = 'LAYER_AGGREGATE_COLOR_SELECT_IID'