export const STARTER_PACK_GENERAL_IID = 'STARTER_PACK_GENERAL_IID';

export const STAGE_DEFAULT_UNDERWATER_IID = 'STAGE_DEFAULT_UNDERWATER_IID'
export const STAGE_DEFAULT_SPACE_IID = 'STAGE_DEFAULT_SPACE_IID'
export const STAGE_DEFAULT_OVERHEAD_IID = 'STAGE_DEFAULT_OVERHEAD_IID'
export const STAGE_DEFAULT_PLATFORMER_IID = 'STAGE_DEFAULT_PLATFORMER_IID'
