export const RELATION_SPAWN_ENTITY_MODEL_IID = "RELATION_SPAWN_ENTITY_MODEL_IID";
export const RELATION_SPAWN_ZONE_ENTITY_IID = "RELATION_SPAWN_ZONE_ENTITY_IID";
export const COLLIDER_RELATION_TAG_IID = "COLLIDER_RELATION_TAG_IID";

export const hideableInterfaceIds = [
  RELATION_SPAWN_ENTITY_MODEL_IID,
  RELATION_SPAWN_ZONE_ENTITY_IID,
  COLLIDER_RELATION_TAG_IID,
]