export const movementInterfaceIds = {
  "movement": {},
  "movement/toggle": {},
  "movement/toggle/ignoreGravity": {},
  "movement/speed": {},
  "movement/gravity": {},
  "movement/gravity/vertical": {},
  "movement/gravity/horizontal": {},
  "movement/sliders": {},
  "movement/sliders/drag": {},
  "movement/sliders/drag/vertical": {},
  "movement/sliders/drag/horizontal": {},
  "movement/pattern": {},
  "movement/velocity": {},
  "movement/velocity/vertical": {},
  "movement/velocity/horizontal": {},
  "movement/controls": {},
  "movement/controls/type": {},
  "movement/controls/disableDownKey": {},
}