export const PROJECTILE_ENTITY_SELECTOR_IID = 'projectile/selector'
export const PROJECTILE_ENTITY_TARGET_SELECTOR_IID = 'projectile/target'
export const PROJECTILE_COOLDOWN_IID = 'projectile/cooldown'
export const PROJECTILE_LIFETIME_IID = 'projectile/lifetime'
export const PROJECTILE_SPEED_IID = 'projectile/speed'