export const RELATION_TAG_ADD_IID = 'relationTag/add'
export const RELATION_TAG_SELECT_IID = 'relationTag/select'
export const RELATION_TAG_CONTAINER_IID = 'relationTag/*'

// NO DATA
export const RELATION_TAG_GENERAL_IID = 'RELATION_TAG_GENERAL_IID';
export const RELATION_TAG_SCRIPT_IID = 'RELATION_TAG_SCRIPT_IID';
export const RELATION_TAG_CUTSCENE_IID = 'RELATION_TAG_CUTSCENE_IID';
export const RELATION_TAG_ENTITY_IID = 'RELATION_TAG_ENTITY_IID';
export const RELATION_TAG_TELEPORT_IID = 'RELATION_TAG_TELEPORT_IID';
export const RELATION_TAG_TRANSFORM_IID = 'RELATION_TAG_TRANSFORM_IID';
export const RELATION_TAG_SPAWN_IID = 'RELATION_TAG_SPAWN_IID';