export const TOGGLE_ALL_PARAMS_IID = 'selector/toggleAllParams';
export const GAME_VIEW_INSTANCE_VISIBILITY_IID = 'selector/layerInvisibility';
export const HOVER_PREVIEW_IID = "selector/hoverPreview";
export const CHANGE_SELECTOR_TABS_IID = "selector/changeTab";
export const CLICK_PREVIEW_IID = "selector/clickPreview";


// NO DATA BELOW HERE 
export const SELECTOR_MORE_IID = "selector/more";

export const SELECT_ENTITY_MODEL_IID = 'SELECT_ENTITY_MODEL'
export const SELECT_RELATION_TAG_IID = 'SELECT_RELATION_TAG'

export const SELECTOR_ENTITY_BY_INTERFACE_ID_IID = 'SELECTOR_ENTITY_BY_INTERFACE_ID_IID'
export const SELECTOR_ENTITY_BY_TAG_LIST_IID = 'SELECTOR_ENTITY_BY_TAG_LIST'
export const SELECTOR_ENTITY_MODEL_DETAIL_IID = 'SELECTOR_ENTITY_MODEL_DETAIL'
export const SELECTOR_RELATION_SYSTEM_IID = 'SELECTOR_RELATION_SYSTEM'
export const SELECTOR_BRUSH_LIST_IID = 'SELECTOR_BRUSH_LIST'
export const SELECTOR_CONTENT_LIST_IID = 'SELECTOR_MEDIA_LIST'
export const SELECTOR_PROMPT_ENTRY_IID = 'SELECTOR_PROMPT_ENTRY'

export const IS_DATA_REMOVED_IID = 'IS_DATA_REMOVED_IID'
export const IS_DATA_HIDDEN_IID = 'IS_DATA_HIDDEN_IID'

export const EFFECT_IID = 'EFFECT_IID'
export const EVENT_IID = 'EVENT_IID'
export const RELATION_IID = 'RELATION_IID'
export const RELATION_TAG_IID = 'RELATION_TAG_IID'


