
export const TOOL_COBROWSING_BROWSER_IID = 'TOOL_COBROWSING_BROWSER_IID';
export const TOOL_COBROWSING_UNLOCK_IID = 'TOOL_COBROWSING_UNLOCK_IID';
export const TOOL_COBROWSING_WIGGLE_IID = 'TOOL_COBROWSING_WIGGLE_IID';
export const TOOL_COBROWSING_ACTIVE_TOGGLE_IID = 'TOOL_COBROWSING_ACTIVE_TOGGLE_IID';

export const TOOL_GRID_MODE_IID = 'TOOL_GRID_MODE_IID';
export const TOOL_CAMERA_IID = 'TOOL_CAMERA_IID';
export const TOOL_BOUNDARY_EDITOR_IID = 'TOOL_BOUNDARY_EDITOR_IID';
export const TOOL_ACTION_PROMPT_IID = 'TOOL_ACTION_PROMPT_IID';
export const TOOL_PLAYTEST_IID = 'TOOL_PLAYTEST_IID';

export const TOOL_GAME_ACTION_IID = 'TOOL_GAME_ACTION_IID';

export const TOOLBAR_MORE_IID = 'TOOLBAR_MORE_IID';

// is toolbars per user? or what? per user per game?, Where I keep all these toolbar tools?
// users -> Game -> toolbar setup