// NO DATA
export const GAME_ROOM_VIDEO_IID = 'GAME_ROOM_VIDEO_IID'
export const PEEK_VIDEO_IID = 'PEEK_VIDEO_IID'
export const VIDEO_ACTIVITY_VIDEO_IID = 'VIDEO_ACTIVITY_VIDEO_IID'
export const LOBBY_MEMBER_VIDEO_IID = 'LOBBY_MEMBER_VIDEO_IID'
export const PARTICIPANT_VIDEO_IID = 'PARTICIPANT_VIDEO_IID'