export const GAME_EDITOR_EXPERIENCE = 'GAME_EDITOR_EXPERIENCE'
export const WAITING_EXPERIENCE = 'WAITING_EXPERIENCE'
export const MONOLOGUE_EXPERIENCE = 'MONOLOGUE_EXPERIENCE'
export const CONVERSATION_EXPERIENCE = 'CONVERSATION_EXPERIENCE'
export const CHATROOM_EXPERIENCE = 'CHATROOM_EXPERIENCE'
export const CREDITS_EXPERIENCE = 'CREDITS_EXPERIENCE'
export const SERVICE_EXPERIENCE = 'SERVICE_EXPERIENCE'

export const experienceStateKeyToDisplayName = {
  [CHATROOM_EXPERIENCE]: 'Chat Room',
  [WAITING_EXPERIENCE]: 'Waiting to start',
  [MONOLOGUE_EXPERIENCE]: 'Monologue',
  [GAME_EDITOR_EXPERIENCE]: 'Game',
  [CREDITS_EXPERIENCE]: 'Credits',
}

export const ADMIN_ROLE = 'ADMIN'
export const ON_MY_VIDEO_QUALITY_STATUS_UPDATE = 'ON_MY_VIDEO_QUALITY_STATUS_UPDATE'

export const PHASER_ERROR = 'PHASER_ERROR'
export const GAME_SESSION_CONNECTION_LOST = 'GAME_SESSION_CONNECTION_LOST'
export const COBROWSING_CONNECTION_LOST = 'COBROWSING_CONNECTION_LOST'
export const CODRAWING_CONNECTION_LOST = 'CODRAWING_CONNECTION_LOST'

export const SOCKET_CONNECTION_LOST = 'SOCKET_CONNECTION_LOST'
export const INTERNET_SPEED_TEST_FAIL = 'INTERNET_SPEED_TEST_FAIL'

export const LOBBY_USER_PRESENT_DELTA = 15000