export const GAME_EDITOR_EXPERIENCE = 'GAME_EDITOR_EXPERIENCE'
export const WAITING_EXPERIENCE = 'WAITING_EXPERIENCE'
export const MONOLOGUE_EXPERIENCE = 'MONOLOGUE_EXPERIENCE'
export const CONVERSATION_EXPERIENCE = 'CONVERSATION_EXPERIENCE'
export const CHATROOM_EXPERIENCE = 'CHATROOM_EXPERIENCE'
export const CREDITS_EXPERIENCE = 'CREDITS_EXPERIENCE'

export const experienceStateKeyToDisplayName = {
  [CHATROOM_EXPERIENCE]: 'Chat Room',
  [WAITING_EXPERIENCE]: 'Waiting to start',
  [MONOLOGUE_EXPERIENCE]: 'Monologue',
  [GAME_EDITOR_EXPERIENCE]: 'Game',
  [CREDITS_EXPERIENCE]: 'Credits',
}