export const INTERFACE_FORM_SLIDER = 'INTERFACE_FORM_SLIDER'
export const INTERFACE_FORM_TEXT = 'INTERFACE_FORM_TEXT'
export const INTERFACE_FORM_TEXTAREA = 'INTERFACE_FORM_TEXTAREA'
export const INTERFACE_FORM_COLOR = 'INTERFACE_FORM_COLOR'
export const INTERFACE_FORM_SELECT = 'INTERFACE_FORM_SELECT'
export const INTERFACE_FORM_CHECKBOX = 'INTERFACE_FORM_CHECKBOX'
export const INTERFACE_FORM_SWITCH = 'INTERFACE_FORM_SWITCH'

export const interfaceFormToDisplayNames = {
  [INTERFACE_FORM_SLIDER]: 'Slider',
  [INTERFACE_FORM_TEXT]: 'Text',
  [INTERFACE_FORM_TEXTAREA]: 'Text Area',
  [INTERFACE_FORM_COLOR]: 'Color',
  [INTERFACE_FORM_SELECT]: 'Select',
  [INTERFACE_FORM_CHECKBOX]: 'Checkbox',
  [INTERFACE_FORM_SWITCH]: 'Switch',
}