export const INSTRUCTION_CATEGORY_GAME_INSTANCE = 'INSTRUCTION_CATEGORY_GAME_INSTANCE'
export const INSTRUCTION_CATEGORY_LOBBY = 'INSTRUCTION_CATEGORY_LOBBY'
export const INSTRUCTION_CATEGORY_GAME_ROOM = 'INSTRUCTION_CATEGORY_GAME_ROOM'
