import { LAYER_ID_PREFIX } from "../constants";

export const STAGE_BACKGROUND_LAYER_CANVAS_DEPTH = 0;

export const BACKGROUND_LAYER_CANVAS_DEPTH = 100;
export const PLAYGROUND_LAYER_CANVAS_DEPTH = 300;
export const FOREGROUND_LAYER_CANVAS_DEPTH = 500;

export const IMAGE_CANVAS_MODAL_CANVAS_DEPTH = 700;
export const UI_CANVAS_DEPTH = 900;

export const STAGE_BACKGROUND_LAYER_CANVAS_ID = 'STAGE_BACKGROUND_LAYER_CANVAS';
export const BACKGROUND_LAYER_CANVAS_ID = 'BACKGROUND_LAYER_CANVAS';
export const IMAGE_CANVAS_MODAL_CANVAS_ID = 'IMAGE_CANVAS_MODAL_CANVAS';
export const PLAYGROUND_LAYER_CANVAS_ID = 'PLAYGROUND_LAYER_CANVAS';
export const FOREGROUND_LAYER_CANVAS_ID = 'FOREGROUND_LAYER_CANVAS';
export const UI_CANVAS_ID = 'UI_CANVAS';

export const LAYER_DEPTH_CATEGORY_BACKGROUND = 'LAYER_DEPTH_CATEGORY_BACKGROUND'
export const LAYER_DEPTH_CATEGORY_PLAYGROUND = 'LAYER_DEPTH_CATEGORY_PLAYGROUND'
export const LAYER_DEPTH_CATEGORY_FOREGROUND = 'LAYER_DEPTH_CATEGORY_FOREGROUND'

export const defaultLayer = {
  layerId: null,
  textureId: null,
  hasCollisionBody: false,
  depthCategory: null
}

export const depthCategoryToDepth = {
  [LAYER_DEPTH_CATEGORY_BACKGROUND] : BACKGROUND_LAYER_CANVAS_DEPTH,
  [LAYER_DEPTH_CATEGORY_FOREGROUND] : FOREGROUND_LAYER_CANVAS_DEPTH,
  [LAYER_DEPTH_CATEGORY_PLAYGROUND] : PLAYGROUND_LAYER_CANVAS_DEPTH
}

export const layerToDisplayName = {
  [LAYER_ID_PREFIX+BACKGROUND_LAYER_CANVAS_ID]: 'Background',
  [LAYER_ID_PREFIX+PLAYGROUND_LAYER_CANVAS_ID]: 'Playground',
  [LAYER_ID_PREFIX+FOREGROUND_LAYER_CANVAS_ID]: 'Foreground',
}