import { LAYER_ID_PREFIX } from "../constants";

export const STAGE_LAYER_DEPTH = 0;

export const BACKGROUND_LAYER_DEPTH = 100;
export const PLAYGROUND_LAYER_GROUP_DEPTH = 300;
export const FOREGROUND_LAYER_GROUP_DEPTH = 500;

export const CANVAS_IMAGE_MODAL_LAYER_DEPTH = 700;
export const UI_LAYER_DEPTH = 900;

export const STAGE_LAYER_ID = 'STAGE_LAYER';
export const BACKGROUND_LAYER_ID = 'BACKGROUND_LAYER';
export const CANVAS_IMAGE_LAYER_ID = 'CANVAS_IMAGE_MODAL_LAYER';
export const PLAYGROUND_LAYER_ID = 'PLAYGROUND_LAYER';
export const FOREGROUND_LAYER_ID = 'FOREGROUND_LAYER';
export const UI_LAYER_ID = 'UI_CANVAS';

export const LAYER_GROUP_ID_BACKGROUND = 'LAYER_GROUP_ID_BACKGROUND'
export const LAYER_GROUP_ID_PLAYGROUND = 'LAYER_GROUP_ID_PLAYGROUND'
export const LAYER_GROUP_ID_FOREGROUND = 'LAYER_GROUP_ID_FOREGROUND'

export const defaultLayer = {
  layerId: null,
  textureId: null,
  hasCollisionBody: false,
  layerGroupId: null
}

export const layerGroupIdToDepth = {
  [LAYER_GROUP_ID_BACKGROUND] : BACKGROUND_LAYER_DEPTH,
  [LAYER_GROUP_ID_FOREGROUND] : FOREGROUND_LAYER_GROUP_DEPTH,
  [LAYER_GROUP_ID_PLAYGROUND] : PLAYGROUND_LAYER_GROUP_DEPTH
}

export const layerToDisplayName = {
  [LAYER_ID_PREFIX+BACKGROUND_LAYER_ID]: 'Background',
  [LAYER_ID_PREFIX+PLAYGROUND_LAYER_ID]: 'Playground',
  [LAYER_ID_PREFIX+FOREGROUND_LAYER_ID]: 'Foreground',
}