import { RELATION_TAG_ID_PREFIX } from "../"

export const RELATION_TAG_LIBRARY = 'RELATION_TAG_LIBRARY';
export const RELATION_TAG_DIALOGUE = 'RELATION_TAG_DIALOGUE';
export const RELATION_TAG_CUTSCENE = 'RELATION_TAG_CUTSCENE';
export const RELATION_TAG_CLASS = 'RELATION_TAG_CLASS';
export const RELATION_TAG_TELEPORT = 'RELATION_TAG_TELEPORT';
export const RELATION_TAG_TRANSFORM = 'RELATION_TAG_TRANSFORM';
export const RELATION_TAG_SPAWN = 'RELATION_TAG_SPAWN';


export const relationTagTypeToDisplayName = {
  RELATION_TAG_LIBRARY: 'Library',
  RELATION_TAG_DIALOGUE: 'Dialogue',
  RELATION_TAG_CUTSCENE: 'Cutscene',
  RELATION_TAG_TELEPORT: 'Teleport',
  RELATION_TAG_TRANSFORM: 'Transform',
  RELATION_TAG_SPAWN: 'Spawn'
}

export const defaultTag = {
  relationTagInterfaceType: null,
  isAutogenerated: false,
  relationTagId: null,
  name: null,
  textureTint: null,
  textureId: null,
  isInterfaceLocked: false,
  isAutoapplied: false
}

function createLibraryTag(relationTagId, name, textureTint, isAutoapplied) {
  return {
    ...defaultTag,
    isAutogenerated: true,
    relationTagInterfaceType: RELATION_TAG_LIBRARY,
    relationTagId,
    name,
    textureTint,
    isAutoapplied
  }
}

export const playgroundRelationTagId = RELATION_TAG_ID_PREFIX+'playground'
export const playerRelationTagId = RELATION_TAG_ID_PREFIX+'player'

export const enemyRelationTagId = RELATION_TAG_ID_PREFIX+'enemy'
export const keyRelationTagId = RELATION_TAG_ID_PREFIX+'key'
export const doorRelationTagId = RELATION_TAG_ID_PREFIX+'door'
export const towerRelationTagId = RELATION_TAG_ID_PREFIX+'tower'
export const movingPlatformRelationTagId = RELATION_TAG_ID_PREFIX+'movingPlatform'
export const transformIntoRelationTagId = RELATION_TAG_ID_PREFIX+'transformInto'
export const transformBackRelationTagId = RELATION_TAG_ID_PREFIX+'transformBack'
export const explodeOnDestroyRelationTagId = RELATION_TAG_ID_PREFIX+'explodeOnDestroy'

export const initialTags = {
  [playerRelationTagId]: createLibraryTag(playerRelationTagId, 'Player', '#FFFF00', true),
  [playgroundRelationTagId]: createLibraryTag(playgroundRelationTagId, 'Playground Layer', '#FFFF00', true),
  [enemyRelationTagId]: createLibraryTag(enemyRelationTagId, 'Enemy', '#FF0000'),
  // [towerRelationTagId]: createLibraryTag(towerRelationTagId, 'Tower', '#FF0000'),
  [doorRelationTagId]: createLibraryTag(doorRelationTagId, 'Door', '#FFFFFF'),
  [keyRelationTagId]: createLibraryTag(keyRelationTagId, 'Key', '#FFFFFF'),
  // [movingPlatformRelationTagId]: createLibraryTag(movingPlatformRelationTagId, 'Moving Platform', '#FFFFFF'),
}

// Object.keys(classTypeToDisplayName).forEach((relationTagInterfaceType) => {
//   initialTags[relationTagInterfaceType] = createLibraryTag(relationTagInterfaceType, classTypeToDisplayName[relationTagInterfaceType], '#FFFF00')
// })