export const TEXTURE_TYPE_SNAPSHOT = 'TEXTURE_TYPE_SNAPSHOT'
export const TEXTURE_TYPE_LAYER = 'TEXTURE_TYPE_LAYER'
export const TEXTURE_TYPE_CANVAS = 'TEXTURE_TYPE_CANVAS'
export const TEXTURE_TYPE_SPRITE = 'TEXTURE_TYPE_SPRITE'