// AUTH
export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const AUTHENTICATE_SOCKET_LOADING = 'AUTHENTICATE_SOCKET_LOADING';
export const AUTHENTICATE_SOCKET_SUCCESS = 'AUTHENTICATE_SOCKET_SUCCESS';
export const AUTHENTICATE_SOCKET_FAIL = 'AUTHENTICATE_SOCKET_FAIL';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';

export const CLEAR_REDIRECT = 'CLEAR_REDIRECT'
export const SET_REDIRECT = 'SET_REDIRECT'

export const ON_SOCKET_CONNECT = 'connect';
export const ON_SOCKET_DISCONNECT = 'ON_SOCKET_DISCONNECT';

export const GET_USER = 'GET_USER';

export const ON_AUTHENTICATE_SOCKET_SUCCESS = 'ON_AUTHENTICATE_SOCKET_SUCCESS';
export const ON_AUTHENTICATE_SOCKET_FAIL = 'ON_AUTHENTICATE_SOCKET_FAIL';