// ERROR
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CHANGE_ERROR_STATE = 'CHANGE_ERROR_STATE';
export const CLEAR_ERROR_STATE = 'CLEAR_ERROR_STATE';
export const SET_RECENTLY_FOCUSED = 'SET_RECENTLY_FOCUSED'

// Snackbar
export const CLEAR_SNACKBAR = 'CLEAR_SNACKBAR';
export const ADD_SNACKBAR = 'ADD_SNACKBAR';


// THEME
export const UPDATE_THEME = 'UPDATE_THEME'

export const SET_GAME_INSTANCE = 'SET_GAME_INSTANCE';

export const SET_CANVAS_IMAGE_DIALOG_GAME_INSTANCE = 'SET_CANVAS_IMAGE_DIALOG_GAME_INSTANCE';


// APP SETTINGS
export const GET_APP_SETTINGS_LOADING = 'GET_APP_SETTINGS_LOADING';
export const GET_APP_SETTINGS_SUCCESS = 'GET_APP_SETTINGS_SUCCESS';
export const GET_APP_SETTINGS_FAIL = 'GET_APP_SETTINGS_FAIL';
export const EDIT_APP_SETTINGS_LOADING = 'EDIT_APP_SETTINGS_LOADING';
export const EDIT_APP_SETTINGS_SUCCESS = 'EDIT_APP_SETTINGS_SUCCESS';
export const EDIT_APP_SETTINGS_FAIL = 'EDIT_APP_SETTINGS_FAIL';