export const DRAW_BRUSH_AID = 'DRAW_BRUSH_AID'
export const DRAW_COLOR_AID = 'DRAW_COLOR_AID'
export const DRAW_NEW_COLOR_AID = 'DRAW_NEW_COLOR_AID';
export const DRAW_NEW_BRUSH_AID = 'DRAW_NEW_BRUSH_AID';
