export const EDIT_ENTITY_AID = 'EDIT_ENTITY_AID';
export const EDIT_GAME_METADATA_AID = 'EDIT_GAME_METADATA_AID';

export const EDIT_ENTITY_BEHAVIOR_AID = 'EDIT_ENTITY_BEHAVIOR_AID';

export const EDIT_CURRENT_PLAYER_CAMERA_AID = 'EDIT_CURRENT_PLAYER_CAMERA_AID';
