export const PLACE_ENTITY_AID = 'PLACE_ENTITY_AID'
export const PLACE_PLAYER_ENTITY_AID = 'PLACE_PLAYER_ENTITY_AID';
export const PLACE_NPC_ENTITY_AID = 'PLACE_NPC_ENTITY_AID';
export const PLACE_ZONE_ENTITY_AID = 'PLACE_ZONE_ENTITY_AID';
export const PLACE_BASIC_ENTITY_AID = 'PLACE_BASIC_ENTITY_AID';
