export const RESIZE_INSTANCE_AID = 'RESIZE_INSTANCE_AID';
export const RESIZE_CURRENT_PLAYER_AID = 'RESIZE_CURRENT_PLAYER_AID';
export const RESIZE_CURRENT_PLAYER_CAMERA_AID = 'RESIZE_CURRENT_PLAYER_CAMERA_AID';