export const SCRIPT_DIALOGUE_AID = 'SCRIPT_DIALOGUE_AID'
export const SCRIPT_DIALOGUE_NEW_AID = 'SCRIPT_DIALOGUE_NEW_AID'

export const SCRIPT_CUTSCENE_AID = 'SCRIPT_CUTSCENE_AID'
export const SCRIPT_CUTSCENE_NEW_AID = 'SCRIPT_CUTSCENE_NEW_AID'