export const SNAPSHOT_GAME_AREA_AID = 'SNAPSHOT_GAME_AREA_AID';
export const SNAPSHOT_PLAYER_CAMERA_ZONE_AID = 'SNAPSHOT_PLAYER_CAMERA_ZONE_AID';
export const SNAPSHOT_STAGE_ZONE_AID = 'SNAPSHOT_STAGE_ZONE_AID';