export const DRAW_NEW_SPRITE_FOR_ENTITY_AID = 'DRAW_NEW_SPRITE_FOR_ENTITY_AID';
export const DRAW_NEW_SPRITE_FOR_CURRENT_PLAYER_AID = 'DREW_NEW_SPRITE_FOR_CURRENT_PLAYER_AID';
export const EDIT_CURRENT_PLAYER_GRAPHICS_AID = 'EDIT_CURRENT_PLAYER_GRAPHICS_AID';
export const EDIT_ENTITY_GRAPHICS_AID = 'EDIT_ENTITY_GRAPHICS_AID';