export const EDIT_CURRENT_STAGE_BOUNDARIES_AID = 'EDIT_CURRENT_STAGE_BOUNDARIES_AID';
export const EDIT_CURRENT_STAGE_AID = 'EDIT_CURRENT_STAGE_AID';
export const EDIT_CURRENT_STAGE_BACKGROUND_COLOR_AID = 'EDIT_CURRENT_STAGE_BACKGROUND_COLOR_AID';
export const EDIT_CURRENT_STAGE_PERSPECTIVE_AID = 'EDIT_CURRENT_STAGE_PERSPECTIVE_AID';
