export const COBROWSE_CLICK_TOOL_AID = 'COBROWSE_CLICK_TOOL_AID';
export const COBROWSE_UNLOCK_TOOL_AID = 'COBROWSE_UNLOCK_TOOL_AID';
export const COBROWSE_WIGGLE_TOOL_AID = 'COBROWSE_WIGGLE_TOOL_AID';