export const WRITE_TEXT_SCENE_AID = 'WRITE_TEXT_SCENE_AID'
export const WRITE_TEXT_SCENE_NEW_AID = 'WRITE_TEXT_SCENE_NEW_AID'

export const WRITE_CUTSCENE_AID = 'WRITE_CUTSCENE_AID'
export const WRITE_CUTSCENE_NEW_AID = 'WRITE_CUTSCENE_NEW_AID'