export const WRITE_SCRIPT_AID = 'WRITE_SCRIPT_AID'
export const WRITE_SCRIPT_NEW_AID = 'WRITE_SCRIPT_NEW_AID'

export const WRITE_CUTSCENE_AID = 'WRITE_CUTSCENE_AID'
export const WRITE_CUTSCENE_NEW_AID = 'WRITE_CUTSCENE_NEW_AID'