// EXPERIENCE_MODEL 
export const GET_EXPERIENCE_MODELS_LOADING = 'GET_EXPERIENCE_MODELS_LOADING';
export const GET_EXPERIENCE_MODELS_SUCCESS = 'GET_EXPERIENCE_MODELS_SUCCESS';
export const GET_EXPERIENCE_MODELS_FAIL = 'GET_EXPERIENCE_MODELS_FAIL';

export const GET_EXPERIENCE_MODEL_LOADING = 'GET_EXPERIENCE_MODEL_LOADING';
export const GET_EXPERIENCE_MODEL_SUCCESS = 'GET_EXPERIENCE_MODEL_SUCCESS';
export const GET_EXPERIENCE_MODEL_FAIL = 'GET_EXPERIENCE_MODEL_FAIL';

export const ADD_EXPERIENCE_MODEL_LOADING = 'ADD_EXPERIENCE_MODEL_LOADING';
export const ADD_EXPERIENCE_MODEL_SUCCESS = 'ADD_EXPERIENCE_MODEL_SUCCESS';
export const ADD_EXPERIENCE_MODEL_FAIL = 'ADD_EXPERIENCE_MODEL_FAIL';

export const EDIT_EXPERIENCE_MODEL_LOADING = 'EDIT_EXPERIENCE_MODEL_LOADING';
export const EDIT_EXPERIENCE_MODEL_SUCCESS = 'EDIT_EXPERIENCE_MODEL_SUCCESS';
export const EDIT_EXPERIENCE_MODEL_FAIL = 'EDIT_EXPERIENCE_MODEL_FAIL';

export const DELETE_EXPERIENCE_MODEL_LOADING = 'DELETE_EXPERIENCE_MODEL_LOADING';
export const DELETE_EXPERIENCE_MODEL_SUCCESS = 'DELETE_EXPERIENCE_MODEL_SUCCESS';
export const DELETE_EXPERIENCE_MODEL_FAIL = 'DELETE_EXPERIENCE_MODEL_FAIL';

export const CLEAR_EXPERIENCE_MODEL = 'CLEAR_EXPERIENCE_MODEL';


// LOBBY
export const ON_LOBBY_INSTANCE_EVENT = 'ON_LOBBY_INSTANCE_EVENT';
export const ON_LOBBY_INSTANCE_UPDATE = 'ON_LOBBY_INSTANCE_UPDATE';
export const ON_LOBBY_INSTANCE_MEMBER_STATUS_UPDATE = 'ON_LOBBY_INSTANCE_MEMBER_STATUS_UPDATE';
// export const ON_LOBBY_INSTANCE_SEND_MESSAGE = 'ON_LOBBY_INSTANCE_SEND_MESSAGE';

// LOBBYS
export const GET_LOBBYS_LOADING = 'GET_LOBBYS_LOADING';
export const GET_LOBBYS_SUCCESS = 'GET_LOBBYS_SUCCESS';
export const GET_LOBBYS_FAIL = 'GET_LOBBYS_FAIL';

export const JOIN_LOBBY_LOADING = 'JOIN_LOBBY_LOADING';
export const JOIN_LOBBY_SUCCESS = 'JOIN_LOBBY_SUCCESS';
export const JOIN_LOBBY_FAIL = 'JOIN_LOBBY_FAIL';

export const SEND_LOBBY_MESSAGE_LOADING = 'SEND_LOBBY_MESSAGE_LOADING';
export const SEND_LOBBY_MESSAGE_SUCCESS = 'SEND_LOBBY_MESSAGE_SUCCESS';
export const SEND_LOBBY_MESSAGE_FAIL = 'SEND_LOBBY_MESSAGE_FAIL';

export const LEAVE_LOBBY_LOADING = 'LEAVE_LOBBY_LOADING';
export const LEAVE_LOBBY_SUCCESS = 'LEAVE_LOBBY_SUCCESS';
export const LEAVE_LOBBY_FAIL = 'LEAVE_LOBBY_FAIL';

export const ASSIGN_LOBBY_ROLE_LOADING = 'ASSIGN_LOBBY_ROLE_LOADING';
export const ASSIGN_LOBBY_ROLE_SUCCESS = 'ASSIGN_LOBBY_ROLE_SUCCESS';
export const ASSIGN_LOBBY_ROLE_FAIL = 'ASSIGN_LOBBY_ROLE_FAIL';

export const TOGGLE_LOBBY_DASHBOARD = 'TOGGLE_LOBBY_DASHBOARD';

export const ADD_LOBBY_LOADING = 'ADD_LOBBY_LOADING';
export const ADD_LOBBY_SUCCESS = 'ADD_LOBBY_SUCCESS';
export const ADD_LOBBY_FAIL = 'ADD_LOBBY_FAIL';

export const GET_LOBBY_LOADING = 'GET_LOBBY_LOADING';
export const GET_LOBBY_SUCCESS = 'GET_LOBBY_SUCCESS';
export const GET_LOBBY_FAIL = 'GET_LOBBY_FAIL';

export const EDIT_LOBBY_LOADING = 'EDIT_LOBBY_LOADING';
export const EDIT_LOBBY_SUCCESS = 'EDIT_LOBBY_SUCCESS';
export const EDIT_LOBBY_FAIL = 'EDIT_LOBBY_FAIL';

export const UPDATE_LOBBY_USER_LOADING = 'UPDATE_LOBBY_USER_LOADING';
export const UPDATE_LOBBY_USER_SUCCESS = 'UPDATE_LOBBY_USER_SUCCESS';
export const UPDATE_LOBBY_USER_FAIL = 'UPDATE_LOBBY_USER_FAIL';

export const DELETE_LOBBY_LOADING = 'DELETE_LOBBY_LOADING';
export const DELETE_LOBBY_SUCCESS = 'DELETE_LOBBY_SUCCESS';
export const DELETE_LOBBY_FAIL = 'DELETE_LOBBY_FAIL';

export const RESEED_DATABASE_LOADING = 'RESEED_DATABASE_LOADING';
export const RESEED_DATABASE_SUCCESS = 'RESEED_DATABASE_SUCCESS';
export const RESEED_DATABASE_FAIL = 'RESEED_DATABASE_FAIL';

export const START_VIDEO_CALL_LOADING = 'START_VIDEO_CALL_LOADING';
export const START_VIDEO_CALL_SUCCESS = 'START_VIDEO_CALL_SUCCESS';
export const START_VIDEO_CALL_FAIL = 'START_VIDEO_CALL_FAIL';
export const LEAVE_VIDEO_CALL_SUCCESS = 'LEAVE_VIDEO_CALL_SUCCESS';
export const LEAVE_VIDEO_CALL_FAIL = 'LEAVE_VIDEO_CALL_FAIL';
export const BYPASS_VIDEO_CALL = 'BYPASS_VIDEO_CALL';
export const SET_VIDEO_TRACK_INTERFACE_ID_OPEN = 'SET_VIDEO_TRACK_INTERFACE_ID_OPEN';
export const SET_VIDEO_TRACK_INTERFACE_ID_CLOSED = 'SET_VIDEO_TRACK_INTERFACE_ID_CLOSED';
export const SET_CURRENT_VIDEO_TRACK_INTERFACE_ID = 'SET_CURRENT_VIDEO_TRACK_INTERFACE_ID';

export const SET_CUT_VIDEO = 'SET_CUT_VIDEO';
export const SET_CUT_AUDIO = 'SET_CUT_AUDIO';

export const SET_VIDEO_TRACK_ID = 'SET_VIDEO_TRACK_ID';
export const SET_AUDIO_TRACK_ID = 'SET_AUDIO_TRACK_ID';