export const ON_GAME_CHARACTER_UPDATE = 'ON_GAME_CHARACTER_UPDATE';
export const ON_GAME_INSTANCE_EVENT = 'ON_GAME_INSTANCE_EVENT';
export const ON_GAME_INSTANCE_UPDATE = 'ON_GAME_INSTANCE_UPDATE';
export const ON_GAME_INSTANCE_UPDATE_ACKNOWLEDGED = 'ON_GAME_INSTANCE_UPDATE_ACKNOWLEDGED';
export const ON_GAME_MODEL_UPDATE = 'ON_GAME_MODEL_UPDATE';

export const TOGGLE_SELECTOR_ENTITY_INVISIBILITY = 'TOGGLE_SELECTOR_ENTITY_INVISIBILITY';

// GAME SESSION
export const ADD_GAME_ROOM_LOADING = 'ADD_GAME_ROOM_LOADING';
export const ADD_GAME_ROOM_SUCCESS = 'ADD_GAME_ROOM_SUCCESS';
export const ADD_GAME_ROOM_FAIL = 'ADD_GAME_ROOM_FAIL';

export const GAME_ROOM_UNDO_LOADING = 'GAME_ROOM_UNDO_LOADING';
export const GAME_ROOM_UNDO_SUCCESS = 'GAME_ROOM_UNDO_SUCCESS';
export const GAME_ROOM_UNDO_FAIL = 'GAME_ROOM_UNDO_FAIL';

export const GET_GAME_ROOM_LOADING = 'GET_GAME_ROOM_LOADING';
export const GET_GAME_ROOM_SUCCESS = 'GET_GAME_ROOM_SUCCESS';
export const GET_GAME_ROOM_FAIL = 'GET_GAME_ROOM_FAIL';

export const SEND_GAME_ROOM_MESSAGE_LOADING = 'SEND_GAME_ROOM_MESSAGE_LOADING';
export const SEND_GAME_ROOM_MESSAGE_SUCCESS = 'SEND_GAME_ROOM_MESSAGE_SUCCESS';
export const SEND_GAME_ROOM_MESSAGE_FAIL = 'SEND_GAME_ROOM_MESSAGE_FAIL';

export const EDIT_GAME_ROOM_LOADING = 'EDIT_GAME_ROOM_LOADING';
export const EDIT_GAME_ROOM_SUCCESS = 'EDIT_GAME_ROOM_SUCCESS';
export const EDIT_GAME_ROOM_FAIL = 'EDIT_GAME_ROOM_FAIL';

export const UPDATE_GAME_ROOM_USER_LOADING = 'UPDATE_GAME_ROOM_USER_LOADING';
export const UPDATE_GAME_ROOM_USER_SUCCESS = 'UPDATE_GAME_ROOM_USER_SUCCESS';
export const UPDATE_GAME_ROOM_USER_FAIL = 'UPDATE_GAME_ROOM_USER_FAIL';

export const DELETE_GAME_ROOM_LOADING = 'DELETE_GAME_ROOM_LOADING';
export const DELETE_GAME_ROOM_SUCCESS = 'DELETE_GAME_ROOM_SUCCESS';
export const DELETE_GAME_ROOM_FAIL = 'DELETE_GAME_ROOM_FAIL';

export const LEAVE_GAME_ROOM_LOADING = 'LEAVE_GAME_ROOM_LOADING';
export const LEAVE_GAME_ROOM_SUCCESS = 'LEAVE_GAME_ROOM_SUCCESS';
export const LEAVE_GAME_ROOM_FAIL = 'LEAVE_GAME_ROOM_FAIL';

export const JOIN_GAME_ROOM_LOADING = 'JOIN_GAME_ROOM_LOADING';
export const JOIN_GAME_ROOM_SUCCESS = 'JOIN_GAME_ROOM_SUCCESS';
export const JOIN_GAME_ROOM_FAIL = 'JOIN_GAME_ROOM_FAIL';

export const ON_GAME_ROOM_INSTANCE_MEMBER_STATUS_UPDATE = 'ON_GAME_ROOM_INSTANCE_MEMBER_STATUS_UPDATE';

export const END_GAME_ROOM = 'END_GAME_ROOM';

export const CHANGE_SELECTOR_COLUMN = "CHANGE_SELECTOR_COLUMN"

export const ADD_IMPORTED_ARCADE_GAME_LOADING  = 'ADD_IMPORTED_ARCADE_GAME_LOADING';
export const ADD_IMPORTED_ARCADE_GAME_SUCCESS = 'ADD_IMPORTED_ARCADE_GAME_SUCCESS';
export const ADD_IMPORTED_ARCADE_GAME_FAIL = 'ADD_IMPORTED_ARCADE_GAME_FAIL';


// COBROWSING 
export const ON_COBROWSING_UPDATE = 'ON_COBROWSING_UPDATE';
export const ON_COBROWSING_STATUS_UPDATE = 'ON_COBROWSING_STATUS_UPDATE';
export const ON_COBROWSING_SUBSCRIBED = 'ON_COBROWSING_SUBSCRIBED';
export const ON_COBROWSING_REMOTE_DISPATCH = 'ON_COBROWSING_REMOTE_DISPATCH';
export const ON_CLEAR_COBROWSING_STATUS = 'ON_CLEAR_COBROWSING_STATUS';
export const COBROWSING_REMOTE_DISPATCH_FAIL = 'COBROWSING_REMOTE_DISPATCH_FAIL';

export const START_COBROWSING_SUCCESS = 'PUBLISH_COBROWSING_SUCCESS';
export const START_COBROWSING_FAIL = 'PUBLISH_COBROWSING_FAIL';

export const END_COBROWSING_SUCCESS = 'END_COBROWSING_SUCCESS';
export const END_COBROWSING_FAIL = 'END_COBROWSING_FAIL';

export const UPDATE_COBROWSING_FAIL = 'UPDATE_COBROWSING_FAIL'

export const SUBSCRIBE_COBROWSING_LOADING = 'SUBSCRIBE_COBROWSING_LOADING';
export const SUBSCRIBE_COBROWSING_SUCCESS = 'SUBSCRIBE_COBROWSING_SUCCESS';
export const SUBSCRIBE_COBROWSING_FAIL = 'SUBSCRIBE_COBROWSING_FAIL';

export const UNSUBSCRIBE_COBROWSING_LOADING = 'UNSUBSCRIBE_COBROWSING_LOADING';
export const UNSUBSCRIBE_COBROWSING_SUCCESS = 'UNSUBSCRIBE_COBROWSING_SUCCESS';
export const UNSUBSCRIBE_COBROWSING_FAIL = 'UNSUBSCRIBE_COBROWSING_FAIL';

// CUTSCENES

export const OPEN_CUTSCENE = 'OPEN_CUTSCENE';
export const PROGRESS_CUTSCENE = 'PROGRESS_CUTSCENE';
export const CLOSE_CUTSCENE = 'CLOSE_CUTSCENE';

// CONSTELLATION
export const START_OPEN_CONSTELLATION = 'START_OPEN_CONSTELLATION';
export const OPEN_CONSTELLATION = 'OPEN_CONSTELLATION';
export const START_CLOSE_CONSTELLATION = 'START_CLOSE_CONSTELLATION';
export const COMPLETE_CLOSE_CONSTELLATION = 'COMPLETE_CLOSE_CONSTELLATION';
export const CLEAR_CUTSCENES = 'CLEAR_CUTSCENES';


export const SET_IS_PLAYER_PAUSED = 'SET_IS_PLAYER_PAUSED';









export const OPEN_GAME_TEXTURES_DIALOG = 'OPEN_GAME_TEXTURES_DIALOG';
export const CLOSE_GAME_TEXTURES_DIALOG = 'CLOSE_GAME_TEXTURES_DIALOG';

export const ON_GAME_ROOM_INSTANCE_UPDATE = 'ON_GAME_ROOM_INSTANCE_UPDATE';


export const CHANGE_PLAYER_STATE = 'CHANGE_PLAYER_STATE';
export const CHANGE_PLAYER_ENTITY = 'CHANGE_PLAYER_ENTITY';

export const CHANGE_CURRENT_STAGE = 'CHANGE_CURRENT_STAGE';
export const CHANGE_INTERACT_OPPURTUNITY = 'CHANGE_INTERACT_OPPURTUNITY';

export const SET_MOUSE_OVER_INTERFACE_ID = 'SET_MOUSE_OVER_INTERFACE_ID'
export const SELECT_COBROWSING_TOOL = 'SELECT_COBROWSING_TOOL'


// ARCADE
export const GET_ARCADE_GAMES_LOADING = 'GET_ARCADE_GAMES_LOADING';
export const GET_ARCADE_GAMES_SUCCESS = 'GET_ARCADE_GAMES_SUCCESS';
export const GET_ARCADE_GAMES_FAIL = 'GET_ARCADE_GAMES_FAIL';

export const GET_ARCADE_GAME_LOADING = 'GET_ARCADE_GAME_LOADING';
export const GET_ARCADE_GAME_SUCCESS = 'GET_ARCADE_GAME_SUCCESS';
export const GET_ARCADE_GAME_FAIL = 'GET_ARCADE_GAME_FAIL';







export const LOAD_GAME_MODEL_LOADING = 'LOAD_GAME_MODEL_LOADING';
export const LOAD_GAME_MODEL_SUCCESS = 'LOAD_GAME_MODEL_SUCCESS';
export const LOAD_GAME_MODEL_FAIL = 'LOAD_GAME_MODEL_FAIL';

export const EDIT_GAME_MODEL_LOADING = 'EDIT_GAME_MODEL_LOADING'
export const EDIT_GAME_MODEL_FAIL = 'EDIT_GAME_MODEL_FAIL'

export const ADD_ARCADE_GAME_LOADING = 'ADD_ARCADE_GAME_LOADING';
export const ADD_ARCADE_GAME_SUCCESS = 'ADD_ARCADE_GAME_SUCCESS';
export const ADD_ARCADE_GAME_FAIL = 'ADD_ARCADE_GAME_FAIL';

export const EDIT_ARCADE_GAME_LOADING = 'EDIT_ARCADE_GAME_LOADING';
export const EDIT_ARCADE_GAME_SUCCESS = 'EDIT_ARCADE_GAME_SUCCESS';
export const EDIT_ARCADE_GAME_FAIL = 'EDIT_ARCADE_GAME_FAIL';

export const UNLOAD_GAME_MODEL = 'UNLOAD_GAME_MODEL';

export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';




// GAME SELECTOr
export const OPEN_SELECT_BACKGROUND_COLOR = 'OPEN_SELECT_BACKGROUND_COLOR';
export const CLOSE_SELECT_BACKGROUND_COLOR = 'CLOSE_SELECT_BACKGROUND_COLOR';

export const OPEN_SELECT_AGGREGATE_COLOR = 'OPEN_SELECT_AGGREGATE_COLOR';
export const CLOSE_SELECT_AGGREGATE_COLOR = 'CLOSE_SELECT_AGGREGATE_COLOR';

export const OPEN_JSON_VIEWER = 'OPEN_JSON_VIEWER';
export const CLOSE_JSON_VIEWER = 'CLOSE_JSON_VIEWER';

export const OPEN_ENTITY_LIVE_EDITOR = 'OPEN_ENTITY_LIVE_EDITOR';
export const CLOSE_ENTITY_LIVE_EDITOR = 'CLOSE_ENTITY_LIVE_EDITOR';

export const OPEN_STAGE_LIVE_EDITOR = 'OPEN_STAGE_LIVE_EDITOR';
export const CLOSE_STAGE_LIVE_EDITOR = 'CLOSE_STAGE_LIVE_EDITOR';


export const OPEN_SECTION_EDITOR = 'OPEN_SECTION_EDITOR';
export const CLOSE_SECTION_EDITOR = 'CLOSE_SECTION_EDITOR';
export const CHANGE_EDITOR_CAMERA_ZOOM = 'CHANGE_EDITOR_CAMERA_ZOOM';

export const SET_IS_DIALOG_OVER_GAME_VIEW = 'SET_IS_DIALOG_OVER_GAME_VIEW';

export const SELECT_ENTITY_MODEL = 'SELECT_ENTITY_MODEL';
export const CLEAR_SELECTED_ENTITY_MODEL = 'CLEAR_SELECTED_ENTITY_MODEL';

export const SELECT_BRUSH = 'SELECT_BRUSH';
export const CLEAR_BRUSH = 'CLEAR_BRUSH';

export const GET_SPRITESHEET_DATA_LOADING = 'GET_SPRITESHEET_DATA_LOADING'
export const GET_SPRITESHEET_DATA_SUCCESS = 'GET_SPRITESHEET_DATA_SUCCESS'
export const GET_SPRITESHEET_DATA_FAIL = 'GET_SPRITESHEET_DATA_FAIL'

export const CLEAR_EDITOR_FORMS = 'CLEAR_EDITOR_FORMS'
export const CLEAR_EDITOR = 'CLEAR_EDITOR'
export const CLEAR_GAME_VIEW_EDITOR = 'CLEAR_GAME_VIEW_EDITOR'

export const TOGGLE_COBROWSING = 'TOGGLE_COBROWSING'
export const TOGGLE_MINIMIZE_COBROWSING_CARD = 'TOGGLE_MINIMIZE_COBROWSING_CARD'

export const TOGGLE_GRID_VIEW = 'TOGGLE_GRID_VIEW'
export const TOGGLE_PIXEL_PERFECT_MODE = 'TOGGLE_PIXEL_PERFECT_MODE'

export const CHANGE_ENTITY_ID_HOVERING = 'CHANGE_ENTITY_ID_HOVERING'
export const CHANGE_BRUSH_ID_HOVERING = 'CHANGE_BRUSH_ID_HOVERING'
export const CHANGE_INSTANCE_HOVERING = 'CHANGE_INSTANCE_HOVERING'
export const CHANGE_EFFECT_ID_HOVERING = 'CHANGE_EFFECT_ID_HOVERING'
export const CHANGE_EVENT_ID_HOVERING = 'CHANGE_EVENT_ID_HOVERING'
export const CHANGE_RELATION_ID_HOVERING = 'CHANGE_RELATION_ID_HOVERING'
export const CHANGE_RELATION_TAG_ID_HOVERING = 'CHANGE_RELATION_TAG_ID_HOVERING'
export const CHANGE_KEYBOARD_SHORTCUT_ACTION_ID_HOVERING = 'CHANGE_KEYBOARD_SHORTCUT_ACTION_ID_HOVERING'

export const TOGGLE_LAYER_VISIBILITY = 'TOGGLE_LAYER_VISIBILITY'
export const TOGGLE_GAME_INSTANCE_PAUSED = 'TOGGLE_GAME_INSTANCE_PAUSED'

export const OPEN_SNAPSHOT_TAKER = 'OPEN_SNAPSHOT_TAKER'
export const CLOSE_SNAPSHOT_TAKER = 'CLOSE_SNAPSHOT_TAKER'

export const OPEN_GAME_METADATA_DIALOG = 'OPEN_GAME_METADATA_DIALOG'
export const CLOSE_GAME_METADATA_DIALOG = 'CLOSE_GAME_METADATA_DIALOG'

export const OPEN_ENTITY_BOX_DIALOG = 'OPEN_ENTITY_BOX_DIALOG'
export const CLOSE_ENTITY_BOX_DIALOG = 'CLOSE_ENTITY_BOX_DIALOG'

export const OPEN_TOOL_BOX_DIALOG = 'OPEN_TOOL_BOX_DIALOG'
export const CLOSE_TOOL_BOX_DIALOG = 'CLOSE_TOOL_BOX_DIALOG'

export const OPEN_ENTITY_EDIT_DIALOG = 'OPEN_ENTITY_EDIT_DIALOG'
export const CLOSE_ENTITY_EDIT_DIALOG = 'CLOSE_ENTITY_EDIT_DIALOG'

export const OPEN_EDIT_RELATION_SYSTEM_DIALOG = 'OPEN_EDIT_RELATION_SYSTEM_DIALOG'
export const CLOSE_EDIT_RELATION_SYSTEM_DIALOG = 'CLOSE_EDIT_RELATION_SYSTEM_DIALOG'

export const OPEN_EDIT_CONTENT_DIALOG = 'OPEN_EDIT_CONTENT_DIALOG'
export const CLOSE_EDIT_CONTENT_DIALOG = 'CLOSE_EDIT_CONTENT_DIALOG'


export const OPEN_EDIT_ENTITY_GRAPHICS = 'OPEN_EDIT_ENTITY_GRAPHICS'
export const CLOSE_CREATE_ENTITY_FLOW = 'CLOSE_CREATE_ENTITY_FLOW'
export const UPDATE_CREATE_ENTITY_MODEL = 'UPDATE_CREATE_ENTITY_MODEL'

export const UPDATE_GAME_MODEL_FORM_EDITOR = 'UPDATE_GAME_MODEL_FORM_EDITOR'

export const OPEN_CREATE_CUTSCENE = 'OPEN_CREATE_CUTSCENE'
export const CLOSE_CREATE_CUTSCENE = 'CLOSE_CREATE_CUTSCENE'
export const UPDATE_CREATE_CUTSCENE = 'UPDATE_CREATE_CUTSCENE'

export const OPEN_CUTSCENES_MENU = 'OPEN_CUTSCENES_MENU'
export const CLOSE_CUTSCENES_MENU = 'CLOSE_CUTSCENES_MENU'

export const SET_IS_MOUSE_OVER_GAME_VIEW = 'SET_IS_MOUSE_OVER_GAME_VIEW'

export const OPEN_CREATE_STAGE = 'OPEN_CREATE_STAGE'
export const CLOSE_CREATE_STAGE = 'CLOSE_CREATE_STAGE'
export const UPDATE_CREATE_STAGE = 'UPDATE_CREATE_STAGE'

export const OPEN_CREATE_RELATION = 'OPEN_CREATE_RELATION'
export const CLOSE_CREATE_RELATION = 'CLOSE_CREATE_RELATION'
export const UPDATE_CREATE_RELATION = 'UPDATE_CREATE_RELATION'

export const OPEN_CREATE_RELATION_TAG = 'OPEN_CREATE_RELATION_TAG'
export const CLOSE_CREATE_RELATION_TAG = 'CLOSE_CREATE_RELATION_TAG'
export const UPDATE_CREATE_RELATION_TAG = 'UPDATE_CREATE_RELATION_TAG'

export const OPEN_CREATE_EFFECT = 'OPEN_CREATE_EFFECT'
export const CLOSE_CREATE_EFFECT = 'CLOSE_CREATE_EFFECT'
export const UPDATE_CREATE_EFFECT = 'UPDATE_CREATE_EFFECT'

export const OPEN_EFFECT_PROMPT_DIALOG = 'OPEN_EFFECT_PROMPT_DIALOG'
export const CLOSE_EFFECT_PROMPT_DIALOG = 'CLOSE_EFFECT_PROMPT_DIALOG'

export const OPEN_CREATE_EVENT = 'OPEN_CREATE_EVENT'
export const CLOSE_CREATE_EVENT = 'CLOSE_CREATE_EVENT'
export const UPDATE_CREATE_EVENT = 'UPDATE_CREATE_EVENT'

export const OPEN_CREATE_CANVAS_IMAGE_DIALOG_LOADING = 'OPEN_CREATE_CANVAS_IMAGE_DIALOG_LOADING'
export const OPEN_CREATE_CANVAS_IMAGE_DIALOG = 'OPEN_CREATE_CANVAS_IMAGE_DIALOG'
export const CLOSE_CREATE_CANVAS_IMAGE_DIALOG = 'CLOSE_CREATE_CANVAS_IMAGE_DIALOG'
export const UPDATE_CREATE_CANVAS_IMAGE = 'UPDATE_CREATE_CANVAS_IMAGE'

export const OPEN_CREATE_BRUSH_FLOW = 'OPEN_CREATE_BRUSH_FLOW'
export const UPDATE_CREATE_BRUSH = 'UPDATE_CREATE_BRUSH'
export const CLOSE_CREATE_BRUSH_FLOW = 'CLOSE_CREATE_BRUSH_FLOW'
export const UPDATE_CREATE_BRUSH_STEP = 'UPDATE_CREATE_BRUSH_STEP'

export const UPDATE_OPEN_INTERFACE_ID = 'UPDATE_OPEN_INTERFACE_ID'
export const UPDATE_VERTICAL_LINEAR_STEPPER = 'UPDATE_VERTICAL_LINEAR_STEPPER'
export const UPDATE_NESTED_LIST = 'UPDATE_NESTED_LIST'

export const OPEN_CREATE_COLOR_FLOW = 'OPEN_CREATE_COLOR_FLOW'
export const TOGGLE_EYE_DROPPER = 'TOGGLE_EYE_DROPPER'
export const CLOSE_CREATE_COLOR_FLOW = 'CLOSE_CREATE_COLOR_FLOW'

export const UPDATE_BRUSH_SIZE = 'UPDATE_BRUSH_SIZE'


export const UNDO_INSTANCE_CHANGE_SUCCESS = 'UNDO_INSTANCE_CHANGE_SUCCES'
export const UNDO_INSTANCE_CHANGE_FAIL = 'UNDO_INSTANCE_CHANGE_FAIL'


export const GAME_INSTANCE_UNDO_LOADING = 'GAME_INSTANCE_UNDO_LOADING';
export const GAME_INSTANCE_UNDO_SUCCESS = 'GAME_INSTANCE_UNDO_SUCCESS';
export const GAME_INSTANCE_UNDO_FAIL = 'GAME_INSTANCE_UNDO_FAIL';
export const ON_GAME_ROOM_INSTANCE_UNDO = 'ON_GAME_ROOM_INSTANCE_UNDO';


export const SET_RESIZING_ENTITY_INSTANCE_ID = 'SET_RESIZING_ENTITY_INSTANCE_ID'