export const spriteSheetIds = {
    'andbandtk': true,
    'overworld-2-8px': true,
    'kenney-voxel-128px': true,
    'kenney-platformer-21px': true,
    'kenney-roguelike-environment-16px': true,
    'kenney-roguelike-dungeon-16px': true,
    'kenney-roguelike-indoor-16px': true,
    'kenney-roguelike-characters-16px': true,
    'kenney-roguelike-city-16px': true,

    'kenney-retro': true,
    // 'kenney-tanks': true,
    // 'kenney-sports-characters-equipment': true,
    // 'kenney-racing-vehicles': true,
    // 'kenney-racing-track': true,
    // 'kenney-racing-characters': true,
    // 'kenney-road': true,
    // 'kenney-racing-stadium': true,
    'lordofthebling-1-16px': true,

    'timefantasy-animations': true,
    'timefantasy-animals': true,
    // 'timefantasy-monsters': true,
    'timefantasy-modern-tiles': true,
    'timefantasy-modern-environment': true,

    'dawnlike-characters': true,
    'dawnlike-creatures2': true,
    'dawnlike-creatures3': true,
    'dawnlike-creatures': true,
    'dawnlike-items': true,
    'dawnlike-environment': true,

    'whtdragon-fish': true,
    'whtdragon-birds': true,
    'whtdragon-mythological': true,
    'whtdragon-predators': true,
    'whtdragon-farm': true,
    'whtdragon-woodland': true,
    'whtdragon-dragons': true,
    'whtdragon-horses': true,
    'whtdragon-pets': true,
    'whtdragon-other': true,
    'whtdragon-lawn': true,
    'whtdragon-reptiles': true,

    // Really we need 3 authors
    // oryx 8px ( 8 bit bundle )
    // oryx 16px ( tiny fantasy, tiny scifi )
    // oryx 24px ( 16 bit bundle )
    // oryx 64px ( ultimate fantasy )
    // oryx roguelike16x24

    //ORYX - 16 bit bundle
    // 'oryx-24px-scifi-environment': true,
    // 'oryx-24px-scifi-transports': true,
    // 'oryx-24px-scifi-characters': true,
    // 'oryx-16px-scifi-items': true,
    // 'oryx-24px-scifi-creatures': true,
    // 'oryx-24px-fantasy-environment': true,
    // 'oryx-24px-fantasy-tiles': true,
    // 'oryx-16px-fantasy-items': true,
    // 'oryx-24px-fantasy-creatures-characters': true,

    //ORYX - 8 bit bundle
    'oryx-lofi-fantasy-creatures-8px': true,
    'oryx-lofi-fantasy-creatures-long-8px': true,
    'oryx-lofi-fantasy-characters-creatures-8px': true,
    'oryx-lofi-fantasy-halls-8px': true,
    'oryx-lofi-fantasy-items-8px': true,
    'oryx-lofi-fantasy-extras-8px': true,
    'oryx-lofi-fantasy-environment-8px': true,

    'oryx-lofi-scifi-creatures-8px': true,
    'oryx-lofi-scifi-creatures-vehicles-large-16px': true,
    'oryx-lofi-scifi-characters-8px': true,
    'oryx-lofi-scifi-vehicles-8px': true,
    'oryx-lofi-scifi-planets': true,
    'oryx-lofi-scifi-items-8px': true,
    'oryx-lofi-scifi-spaceship-environment-8px': true,

    // 'silmar-monsters': true,
    // 'silmar-characters': true,
    // 'silmar-items': true,
    // 'silmar-environment': true,

    // 'has-buildings-16x16': true,
    // 'has-buildings-16x32': true,
    // 'has-buildings-32x16': true,
    // 'has-buildings-32x32': true,
    // 'has-buildings-48x32': true,
    // 'has-buildings-48x48': true,
    // 'has-buildings-64x48': true,
    // 'has-buildings-64x64': true,
    // 'has-monsters': true,
    // 'has-terrain': true,
    // 'has-terrain2': true,
    // 'has-terrain-other': true,
    //
    'candy-1': true,
    'retro-1': true,
    'retro-2-30px': true,
    // 'retro-3-16px': true,
    'retro-4': true,

    'unknownMonsters-1': true,
    //
    'overworld-1-16px': true,
    // 'platformer-1': true,
    'minecraft-1-48px': true,
  }

export const spriteSheetAuthors = {
    slimar: true,
    has: true,
    andbangtk: true,
    lordofthebling: true,
    oryx: true,
    dawnlike: true,
    whtdragon: true,
    timefantasy: true,
    // amsimuz: false,
    // tylerwarren: false,
    kenney: true,
    kenneyRetro: true,
    // shackal: false,
    // unknown: false,
    unknownFromGame: false,
    unknownRetro1: true,
    unknownRetro2: true,
    unknownRetro3: true,
    unknownRetro4: true,
    unknownCandy: false,
    // unknownGlitch: false,
    unknownMonsters1: true,
    unknownOverworld1: true,
    unknownOverworld2: true,
    unknownPlatformer1: false,
  }
