export const ANIMATION_CAMERA_SHAKE = 'ANIMATION_CAMERA_SHAKE'
export const ANIMATION_CONFETTI = 'ANIMATION_CONFETTI'
export const EVENT_SPAWN_MODEL_IN_CAMERA = 'EVENT_SPAWN_MODEL_IN_CAMERA'
export const EVENT_SPAWN_MODEL_DRAG_FINISH = 'EVENT_SPAWN_MODEL_DRAG_FINISH'