export const ANIMATION_CAMERA_SHAKE = 'ANIMATION_CAMERA_SHAKE'
export const ANIMATION_CONFETTI = 'ANIMATION_CONFETTI'
export const EVENT_SPAWN_CLASS_IN_CAMERA = 'EVENT_SPAWN_CLASS_IN_CAMERA'
export const EVENT_SPAWN_CLASS_DRAG_FINISH = 'EVENT_SPAWN_CLASS_DRAG_FINISH'