export const CODRAWING_STROKE_OP = 'CODRAWING_STROKE_OP';
export const CODRAWING_FLIP_X_OP = 'CODRAWING_FLIP_X_OP';
export const CODRAWING_FLIP_Y_OP = 'CODRAWING_FLIP_Y_OP';
export const CODRAWING_ROTATE_OP = 'CODRAWING_ROTATE_OP';

