// CONTROL TYPES
export const CAR_CONTROLS = 'CAR_CONTROLS'
export const VEHICLE_CONTROLS = 'VEHICLE_CONTROLS'
export const DIRECTIONAL_CONTROLS = 'DIRECTIONAL_CONTROLS'
export const ADVANCED_DIRECTIONAL_CONTROLS = 'ADVANCED_DIRECTIONAL_CONTROLS'
