// EFFECTS
export const EFFECT_TELEPORT = 'EFFECT_TELEPORT'
export const EFFECT_FOLLOW_START = 'EFFECT_FOLLOW_START'
export const EFFECT_FOLLOW_END = 'EFFECT_FOLLOW_END'

export const EFFECT_IGNORE_GRAVITY = 'EFFECT_IGNORE_GRAVITY'
export const EFFECT_STICK_TO = 'EFFECT_STICK_TO'

export const EFFECT_TRANSFORM = 'EFFECT_TRANSFORM'
export const EFFECT_SPAWN = 'EFFECT_SPAWN'
export const EFFECT_DESTROY = 'EFFECT_DESTROY'

export const EFFECT_CAMERA_SHAKE = 'EFFECT_CAMERA_SHAKE'
export const EFFECT_INVISIBLE = 'EFFECT_INVISIBLE'

export const EFFECT_SWITCH_STAGE = 'EFFECT_SWITCH_STAGE'

export const EFFECT_PAUSE_GAME = 'EFFECT_PAUSE_GAME'
export const EFFECT_UNPAUSE_GAME = 'EFFECT_UNPAUSE_GAME'

export const EFFECT_INTERFACE_ACTION = 'EFFECT_INTERFACE_ACTION'

export const EFFECT_INTERFACE_UNLOCK = 'EFFECT_INTERFACE_UNLOCK'
// 

/// THIS IS TECHNICALLY ALL GAME STATE/PLAYER STATE CHANGES, WHEN GAME STATE IS IMPLEMENTED WE WILL USE THIS
export const EFFECT_CUTSCENE = 'EFFECT_CUTSCENE'
export const EFFECT_GAME_OVER = 'EFFECT_GAME_OVER'
export const EFFECT_WIN_GAME = 'EFFECT_WIN_GAME'


// ------------

export const SPAWN_ZONE_A_SELECT = 'SPAWN_ZONE_A_SELECT';
export const SPAWN_ZONE_B_SELECT = 'SPAWN_ZONE_B_SELECT';
export const SPAWN_ZONE_RANDOM_SELECT = 'SPAWN_ZONE_RANDOM_SELECT';

