// EVENTS
export const ON_TOUCH_START = 'ON_TOUCH_START'
export const ON_COLLIDE_END = 'ON_COLLIDE_END'
export const ON_TOUCH_ACTIVE = 'ON_TOUCH_ACTIVE'
export const ON_SPAWN = 'ON_SPAWN'
export const ON_PLAYTHROUGH = 'ON_PLAYTHROUGH'
export const ON_DESTROY_ONE = 'ON_DESTROY_ONE'
export const ON_DESTROY_ALL = 'ON_DESTROY_ALL'
export const ON_INTERACT = 'ON_INTERACT'
export const ON_CUTSCENE_END = 'ON_CUTSCENE_END'
export const ON_STEP_BEGINS = 'ON_STEP_BEGINS'

