import { CUTSCENE_DID, ENTITY_INSTANCE_DID, ENTITY_MODEL_DID, PLAYER_ENTITY_TYPE_PREFIX, STAGE_DID, ZONE_ENTITY_TYPE_PREFIX } from "./constants"

export const VEHICLE_PLAYER_ENTITY_ID = ENTITY_MODEL_DID+PLAYER_ENTITY_TYPE_PREFIX+'vehicle'
export const JUMPER_PLAYER_ENTITY_ID = ENTITY_MODEL_DID+PLAYER_ENTITY_TYPE_PREFIX+'jumper'
export const DIRECTIONAL_PLAYER_ENTITY_ID = ENTITY_MODEL_DID+PLAYER_ENTITY_TYPE_PREFIX+'directional'
export const SWIMMER_PLAYER_ENTITY_ID= ENTITY_MODEL_DID+PLAYER_ENTITY_TYPE_PREFIX+'swimmer'

export const INITIAL_STAGE_ID =  STAGE_DID+'default'
export const PLAYER_SPAWN_ZONE_ENTITY_ID = ENTITY_MODEL_DID+ZONE_ENTITY_TYPE_PREFIX+'playerspawnzone'
export const PLAYER_SPAWN_ZONE_INSTANCE_ID = ENTITY_MODEL_DID+ENTITY_INSTANCE_DID+'playerspawnzone'
export const CAMERA_ZONE_ENTITY_ID = ENTITY_MODEL_DID+ZONE_ENTITY_TYPE_PREFIX+'playercamerazone2'
export const CAMERA_ZONE_INSTANCE_ID = ENTITY_MODEL_DID+ENTITY_INSTANCE_DID+'playercamerazone'
export const STAGE_ZONE_ENTITY_ID = ENTITY_MODEL_DID+ZONE_ENTITY_TYPE_PREFIX+'stagezone'
export const STAGE_ZONE_INSTANCE_ID = ENTITY_MODEL_DID+ENTITY_INSTANCE_DID+'stagezone'

export const PLAYTHROUGH_START_CUTSCENE_ID = CUTSCENE_DID+'start'
export const END_GAME_CUTSCENE_ID = CUTSCENE_DID+'end'

export const defaultImportantValue = {
  unique: true,
  type: 'id',
  name: 'New Important Value',
  importantValueId: null,
  //importantValueId: INITIAL_STAGE_ID,
  relatedId: null
}