export const RELATION_TAG_GENERAL_IID = 'RELATION_TAG_GENERAL_IID';
export const RELATION_TAG_DIALOGUE_IID = 'RELATION_TAG_DIALOGUE_IID';
export const RELATION_TAG_CUTSCENE_IID = 'RELATION_TAG_CUTSCENE_IID';
export const RELATION_TAG_ENTITY_IID = 'RELATION_TAG_ENTITY_IID';
export const RELATION_TAG_TELEPORT_IID = 'RELATION_TAG_TELEPORT_IID';
export const RELATION_TAG_TRANSFORM_IID = 'RELATION_TAG_TRANSFORM_IID';
export const RELATION_TAG_SPAWN_IID = 'RELATION_TAG_SPAWN_IID';
