export const RELATION_TAG_LIBRARY = 'RELATION_TAG_LIBRARY';
export const RELATION_TAG_DIALOGUE = 'RELATION_TAG_DIALOGUE';
export const RELATION_TAG_CUTSCENE = 'RELATION_TAG_CUTSCENE';
export const RELATION_TAG_CLASS = 'RELATION_TAG_CLASS';
export const RELATION_TAG_TELEPORT = 'RELATION_TAG_TELEPORT';
export const RELATION_TAG_TRANSFORM = 'RELATION_TAG_TRANSFORM';
export const RELATION_TAG_SPAWN = 'RELATION_TAG_SPAWN';
