export const STAGE_DEFAULT_UNDERWATER = 'STAGE_DEFAULT_UNDERWATER'
export const STAGE_DEFAULT_SPACE = 'STAGE_DEFAULT_SPACE'
export const STAGE_DEFAULT_OVERHEAD = 'STAGE_DEFAULT_OVERHEAD'
export const STAGE_DEFAULT_PLATFORMER = 'STAGE_DEFAULT_PLATFORMER'
