/////////////////////////////////////
/////////////////////////////////////

// WHAT HAPPENS
export const defaultEffect = {
  effectBehavior: '',
  effectId: null,

  remoteEffectedRelationTagIds: [],

  stageId: null,
  spawnEntityClassId: null,
  entityClassId: null,
  arcadeGameMongoId: null,
  zoneEntityClassId: null,
  cutsceneId: null,
  text: '',
  
  isAutogenerated: false,
  isRemoved: false,

  customSelectorCategory: null
}

