// import { BACKGROUND_LAYER_ID } from "../constants";
import { DEFAULT_THEME_COLOR } from "../../../constants";
import { defaultZoneClass, directionalClass, jumperClass, vehicleClass } from "../entityClassDefaults";
import { initialStage } from "./stage";
import { DATA_SOURCE_AUTOGENERATED, directionalPlayerClassId, initialCameraZoneClassId, initialPlayerSpawnZoneClassId, initialStageId, initialStageZoneClassId, jumperPlayerClassId, vehiclePlayerClassId } from "../core";
import { mirrorPlayerDefaults } from "../entityClassPropertyDefaults";
import { PLAYGROUND_LAYER_GROUP_DEPTH } from "../core";
import { nodeSize } from "../core";
import { gameSize } from "../core";

export const defaultGameModel = {
  "metadata": {
    "title": "",
    "description": "",
    "authorPseudonym": "",
    "imageUrl": "",
    isArchived: false,
    isFeatured: false,
    isPublished: false,
  },
  theme: {
    primaryColor: DEFAULT_THEME_COLOR
  },
  "stages": {
     [initialStageId]: {
      ...initialStage,
      stageId: initialStageId
    }
  },
  "nodeSize": nodeSize,
  colors: {

  },
  cutscenes: {

  },
  relations: {

  },
  relationTags: {},
  effects: {},
  events: {},
  "canvasImages": {
    // "url": "xxx",
    // "name": 'name'
    // "type": "layer"
  },
  "player": {
    "lives": 1,
    'startingStageId': initialStageId
  },
  "collisions": {

  },
  "entityClasses": {
    [vehiclePlayerClassId]: vehicleClass,
    [jumperPlayerClassId]: jumperClass,
    [directionalPlayerClassId]: directionalClass,
    [initialPlayerSpawnZoneClassId]: {
      name: 'Player Spawn',
      ...defaultZoneClass,
      entityClassId: initialPlayerSpawnZoneClassId,
      editorInterface: {
        ...defaultZoneClass.editor,
        notVisibleInSelector: true,
        destroyAllEffect: true,
      },
      autogeneration: {
        ...defaultZoneClass.autogeneration,
        transformIntoEffect: true,
        spawnAnywhereEffect: true,
      },
      graphics: {
        ...defaultZoneClass.graphics,
        textureTint: '#FFFFFF',
      },
      dataSource: DATA_SOURCE_AUTOGENERATED
    },
    [initialCameraZoneClassId]: {
      name: 'Player Camera',
      ...defaultZoneClass,
      movement: {
        ...mirrorPlayerDefaults.movement
      },
      editorInterface: {
        ...defaultZoneClass.editor,
        notVisibleInSelector: true,
        fixedAspectRatio: true,
      },
      autogeneration: {
        ...defaultZoneClass.autogeneration,
        destroyAllEffect: true,
        transformIntoEffect: true,
        noSpawnAnywhereTag: true,
        playerTeleportToRelationTag: true
      },
      collisionResponse: {
        ...mirrorPlayerDefaults.collisionResponse,
        ignoreStageBoundaries: true
      },
      entityClassId: initialCameraZoneClassId,
      graphics: {
        ...defaultZoneClass.graphics,
        textureTint: '#00FF00',
        depthOverride: PLAYGROUND_LAYER_GROUP_DEPTH - 5,
        width: nodeSize * 28,
        height: nodeSize * 28
      },
      dataSource: DATA_SOURCE_AUTOGENERATED
    },
    [initialStageZoneClassId]: {
      name: 'Stage',
      ...defaultZoneClass,
      editorInterface: {
        ...defaultZoneClass.editor,
        notVisibleInSelector: true,
        notSelectableInStage: true,
      },
      autogeneration: {
        destroyAllEffect: true,
        transformIntoEffect: true,
        teleportToEffect: true,
        spawnAnywhereEffect: true
      },
      collisionResponse: {
        ...mirrorPlayerDefaults.collisionResponse,
        ignoreStageBoundaries: true
      },
      entityClassId: initialStageZoneClassId,
      graphics: {
        ...defaultZoneClass.graphics,
        textureTint: '#000000',
        depthOverride: 1,
        width: gameSize,
        height: gameSize
      },
      dataSource: DATA_SOURCE_AUTOGENERATED,
      isRemoved: true
    }
  },
  isRemoved: false
}

  // spawnX: gameSize/2,
  // spawnY: gameSize/2,