import { RELATION_TAG_ID_PREFIX, RELATION_TAG_LIBRARY } from ".."


export const defaultTag = {
  relationTagInterfaceType: null,
  isAutogenerated: false,
  relationTagId: null,
  name: null,
  textureTint: null,
  textureId: null,
  isSelectorObscured: false,
  hideIfAddingToClass: false,
}

function createLibraryTag(relationTagId, name, textureTint, hideIfAddingToClass) {
  return {
    ...defaultTag,
    isAutogenerated: true,
    relationTagInterfaceType: RELATION_TAG_LIBRARY,
    relationTagId,
    name,
    textureTint,
    hideIfAddingToClass
  }
}

export const playgroundRelationTagId = RELATION_TAG_ID_PREFIX+'playground'
export const playerRelationTagId = RELATION_TAG_ID_PREFIX+'player'

export const enemyRelationTagId = RELATION_TAG_ID_PREFIX+'enemy'
export const keyRelationTagId = RELATION_TAG_ID_PREFIX+'key'
export const doorRelationTagId = RELATION_TAG_ID_PREFIX+'door'
export const towerRelationTagId = RELATION_TAG_ID_PREFIX+'tower'
export const movingPlatformRelationTagId = RELATION_TAG_ID_PREFIX+'movingPlatform'
export const transformIntoRelationTagId = RELATION_TAG_ID_PREFIX+'transformInto'
export const transformBackRelationTagId = RELATION_TAG_ID_PREFIX+'transformBack'
export const explodeOnDestroyRelationTagId = RELATION_TAG_ID_PREFIX+'explodeOnDestroy'

export const initialTags = {
  [playerRelationTagId]: createLibraryTag(playerRelationTagId, 'Player', '#FFFF00', true),
  [playgroundRelationTagId]: createLibraryTag(playgroundRelationTagId, 'Playground Layer', '#FFFF00', true),
  [enemyRelationTagId]: createLibraryTag(enemyRelationTagId, 'Enemy', '#FF0000'),
  // [towerRelationTagId]: createLibraryTag(towerRelationTagId, 'Tower', '#FF0000'),
  [doorRelationTagId]: createLibraryTag(doorRelationTagId, 'Door', '#FFFFFF'),
  [keyRelationTagId]: createLibraryTag(keyRelationTagId, 'Key', '#FFFFFF'),
  // [movingPlatformRelationTagId]: createLibraryTag(movingPlatformRelationTagId, 'Moving Platform', '#FFFFFF'),
}

// Object.keys(classTypeToDisplayName).forEach((relationTagInterfaceType) => {
//   initialTags[relationTagInterfaceType] = createLibraryTag(relationTagInterfaceType, classTypeToDisplayName[relationTagInterfaceType], '#FFFF00')
// })