export const PLAY_GAME_SCOPE_EXPERIENCE_INSTANCE = 'PLAY_GAME_SCOPE_EXPERIENCE_INSTANCE';
export const PLAY_GAME_SCOPE_UNLISTED = 'PLAY_GAME_SCOPE_UNLISTED';
export const PLAY_GAME_SCOPE_USER_PROFILE = 'PLAY_GAME_SCOPE_USER_PROFILE';
// export const PLAY_GAME_SCOPE_FRIENDS = 'PLAY_GAME_SCOPE_FRIENDS';
// export const PLAY_GAME_SCOPE_FRIENDS_OF_FRIENDS = 'PLAY_GAME_SCOPE_FRIENDS_OF_FRIENDS';
export const PLAY_GAME_SCOPE_ARCADE = 'PLAY_GAME_SCOPE_ARCADE';
export const PLAY_GAME_SCOPE_FEATURED = 'PLAY_GAME_SCOPE_FEATURED';

export const EDIT_GAME_SCOPE_EXPERIENCE_INSTANCE = 'EDIT_GAME_SCOPE_EXPERIENCE_INSTANCE';
export const EDIT_GAME_SCOPE_ONLY_ME = 'EDIT_GAME_SCOPE_ONLY_ME';
export const EDIT_GAME_SCOPE_USER_LIST = 'EDIT_GAME_SCOPE_USER_LIST';
export const EDIT_GAME_SCOPE_ANYONE = 'EDIT_GAME_SCOPE_ANYONE';