/* eslint-disable import/no-anonymous-default-export */
import { ADD_BRUSH_IID, BACKGROUND_CANVAS_ADD_BRUSH_IID, BACKGROUND_CANVAS_BRUSH_SELECT_IID, BACKGROUND_CANVAS_COLOR_SELECT_IID, BACKGROUND_CANVAS_CONTAINER_IID, BRUSH_SIZE_IID, FOREGROUND_CANVAS_ADD_BRUSH_IID, FOREGROUND_CANVAS_BRUSH_SELECT_IID, FOREGROUND_CANVAS_COLOR_SELECT_IID, FOREGROUND_CANVAS_CONTAINER_IID, PLAYGROUND_CANVAS_ADD_BRUSH_IID, PLAYGROUND_CANVAS_BRUSH_SELECT_IID, PLAYGROUND_CANVAS_COLOR_SELECT_IID, PLAYGROUND_CANVAS_CONTAINER_IID } from "../interfaceIds";

export default {
  [BRUSH_SIZE_IID]: {},
  [ADD_BRUSH_IID]: {},
  [BACKGROUND_CANVAS_CONTAINER_IID]: {},
  [BACKGROUND_CANVAS_ADD_BRUSH_IID]: {},
  [BACKGROUND_CANVAS_COLOR_SELECT_IID]: {},
  [BACKGROUND_CANVAS_BRUSH_SELECT_IID]: {},
  [PLAYGROUND_CANVAS_CONTAINER_IID]: {},
  [PLAYGROUND_CANVAS_ADD_BRUSH_IID]: {},
  [PLAYGROUND_CANVAS_COLOR_SELECT_IID]: {},
  [PLAYGROUND_CANVAS_BRUSH_SELECT_IID]: {},
  [FOREGROUND_CANVAS_CONTAINER_IID]: {},
  [FOREGROUND_CANVAS_ADD_BRUSH_IID]: {},
  [FOREGROUND_CANVAS_COLOR_SELECT_IID]: {},
  [FOREGROUND_CANVAS_BRUSH_SELECT_IID]: {},
}