import { BASIC_CLASS_ADD_IID, BASIC_CLASS_CONTAINER_IID, BASIC_CLASS_SELECT_IID, CLASS_LAYER_IID, CLASS_LOCKED_IID, CLASS_VISIBILITY_IID, NPC_CLASS_ADD_IID, NPC_CLASS_CONTAINER_IID, NPC_CLASS_SELECT_IID, PLAYER_CLASS_ADD_IID, PLAYER_CLASS_CONTAINER_IID, PLAYER_CLASS_SELECT_IID, ZONE_CLASS_ADD_IID, ZONE_CLASS_CONTAINER_IID, ZONE_CLASS_SELECT_IID } from "../interfaceIds";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  [ZONE_CLASS_CONTAINER_IID]: {},
  [ZONE_CLASS_ADD_IID]: {},
  [ZONE_CLASS_SELECT_IID]: {},
  [BASIC_CLASS_CONTAINER_IID]: {},
  [BASIC_CLASS_ADD_IID]: {},
  [BASIC_CLASS_SELECT_IID]: {},
  [NPC_CLASS_CONTAINER_IID]: {},
  [NPC_CLASS_SELECT_IID]: {},
  [NPC_CLASS_ADD_IID]: {},
  [PLAYER_CLASS_CONTAINER_IID]: {},
  [PLAYER_CLASS_SELECT_IID]: {},
  [PLAYER_CLASS_ADD_IID]: {},
  [CLASS_LAYER_IID]: {},
  [CLASS_VISIBILITY_IID]: {},
  [CLASS_LOCKED_IID]: {},
}