import { CONTEXT_MENU_CLASS_CAMERA_IID, CONTEXT_MENU_CLASS_DUPLICATE_IID, CONTEXT_MENU_CLASS_GRAPHICS_IID, CONTEXT_MENU_CLASS_JUMP_IID, CONTEXT_MENU_CLASS_MOVEMENT_IID, CONTEXT_MENU_CLASS_NAME_IID, CONTEXT_MENU_CLASS_PHYSICS_IID, CONTEXT_MENU_CLASS_PROJECTILE_IID, CONTEXT_MENU_CLASS_RELATIONS_IID, CONTEXT_MENU_CLASS_REMOVE_IID, CONTEXT_MENU_CLASS_SELECT_PLAYER_IID, CONTEXT_MENU_CONTAINER_IID, CONTEXT_MENU_CUTSCENES_IID, CONTEXT_MENU_INSTANCE_DELETE_IID, CONTEXT_MENU_INSTANCE_JSON_IID, CONTEXT_MENU_INSTANCE_MOVE_IID, CONTEXT_MENU_INSTANCE_RESIZE_CLASS_IID, CONTEXT_MENU_INSTANCE_SELECT_CLASS_IID, CONTEXT_MENU_METADATA_IID, CONTEXT_MENU_PLAYTEST_IID, CONTEXT_MENU_SNAPSHOT_IID, CONTEXT_MENU_STAGES_IID, CONTEXT_MENU_STAGE_COLOR_IID, CONTEXT_MENU_STAGE_GRAVITY_IID, CONTEXT_MENU_STAGE_SECTIONS_IID } from "../interfaceIds";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  [CONTEXT_MENU_CONTAINER_IID]: {
    ignoreTools: true
  },
  [CONTEXT_MENU_CLASS_JUMP_IID]: {},
  [CONTEXT_MENU_CLASS_GRAPHICS_IID]: {},
  [CONTEXT_MENU_CLASS_PHYSICS_IID]: {},
  [CONTEXT_MENU_CLASS_MOVEMENT_IID]: {},
  [CONTEXT_MENU_CLASS_RELATIONS_IID]: {},
  [CONTEXT_MENU_CLASS_DUPLICATE_IID]: {},
  [CONTEXT_MENU_CLASS_CAMERA_IID]: {},
  [CONTEXT_MENU_CLASS_PROJECTILE_IID]: {},
  [CONTEXT_MENU_STAGE_GRAVITY_IID]: {},
  [CONTEXT_MENU_STAGE_SECTIONS_IID]: {},
  [CONTEXT_MENU_STAGE_COLOR_IID]: {},
  [CONTEXT_MENU_METADATA_IID]: {},
  [CONTEXT_MENU_SNAPSHOT_IID]: {},
  [CONTEXT_MENU_CUTSCENES_IID]: {},
  [CONTEXT_MENU_INSTANCE_MOVE_IID]: {},
  [CONTEXT_MENU_CLASS_SELECT_PLAYER_IID]: {},
  [CONTEXT_MENU_CLASS_NAME_IID]: {},
  [CONTEXT_MENU_CLASS_REMOVE_IID]: {},
  [CONTEXT_MENU_INSTANCE_RESIZE_CLASS_IID]: {},
  [CONTEXT_MENU_INSTANCE_SELECT_CLASS_IID]: {},
  [CONTEXT_MENU_INSTANCE_DELETE_IID]: {},
  [CONTEXT_MENU_STAGES_IID]: {},
  [CONTEXT_MENU_INSTANCE_JSON_IID]: {
    adminOnly: true
  },
  [CONTEXT_MENU_PLAYTEST_IID]: {
    adminOnly: true 
  }
}