import { CONTEXT_MENU_ENTITY_CAMERA_IID, CONTEXT_MENU_ENTITY_DUPLICATE_IID, CONTEXT_MENU_ENTITY_GRAPHICS_IID, CONTEXT_MENU_ENTITY_JUMP_IID, CONTEXT_MENU_ENTITY_MOVEMENT_IID, CONTEXT_MENU_ENTITY_EDIT_IID, CONTEXT_MENU_ENTITY_COLLISIONS_IID, CONTEXT_MENU_ENTITY_PROJECTILE_IID, CONTEXT_MENU_ENTITY_RELATIONS_IID, CONTEXT_MENU_ENTITY_REMOVE_IID, CONTEXT_MENU_ENTITY_SELECT_PLAYER_IID, CONTEXT_MENU_CONTAINER_IID, CONTEXT_MENU_CUTSCENES_IID, CONTEXT_MENU_INSTANCE_DELETE_IID, CONTEXT_MENU_INSTANCE_JSON_IID, CONTEXT_MENU_INSTANCE_MOVE_IID, CONTEXT_MENU_INSTANCE_RESIZE_ENTITY_IID, CONTEXT_MENU_INSTANCE_SELECT_ENTITY_IID, CONTEXT_MENU_PLAYTEST_IID,  CONTEXT_MENU_STAGES_IID, CONTEXT_MENU_STAGE_GRAVITY_IID, CONTEXT_MENU_STAGE_SECTIONS_IID } from "../interfaceIds";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  [CONTEXT_MENU_CONTAINER_IID]: {
    ignoreTools: true
  },
  [CONTEXT_MENU_ENTITY_JUMP_IID]: {},
  [CONTEXT_MENU_ENTITY_GRAPHICS_IID]: {},
  [CONTEXT_MENU_ENTITY_COLLISIONS_IID]: {},
  [CONTEXT_MENU_ENTITY_MOVEMENT_IID]: {},
  [CONTEXT_MENU_ENTITY_RELATIONS_IID]: {},
  [CONTEXT_MENU_ENTITY_DUPLICATE_IID]: {},
  [CONTEXT_MENU_ENTITY_CAMERA_IID]: {},
  [CONTEXT_MENU_ENTITY_PROJECTILE_IID]: {},
  [CONTEXT_MENU_STAGE_GRAVITY_IID]: {},
  [CONTEXT_MENU_STAGE_SECTIONS_IID]: {},
  [CONTEXT_MENU_CUTSCENES_IID]: {},
  [CONTEXT_MENU_INSTANCE_MOVE_IID]: {},
  [CONTEXT_MENU_ENTITY_SELECT_PLAYER_IID]: {},
  [CONTEXT_MENU_ENTITY_EDIT_IID]: {},
  [CONTEXT_MENU_ENTITY_REMOVE_IID]: {},
  [CONTEXT_MENU_INSTANCE_RESIZE_ENTITY_IID]: {},
  [CONTEXT_MENU_INSTANCE_SELECT_ENTITY_IID]: {},
  [CONTEXT_MENU_INSTANCE_DELETE_IID]: {},
  [CONTEXT_MENU_STAGES_IID]: {},
  [CONTEXT_MENU_INSTANCE_JSON_IID]: {
    adminOnly: true
  },
  [CONTEXT_MENU_PLAYTEST_IID]: {
    adminOnly: true 
  }
}