import { EDIT_ENTITY_AID, IMPORT_DATA_SOURCE_AID, PLACE_ENTITY_AID } from "../interfaceActionIds";
import { COLLIDER_RELATION_TAG_IID, PROJECTILE_ENTITY_SELECTOR_IID, ENTITY_SPAWN_ZONE_ENTITY_IID, RELATION_SPAWN_ENTITY_MODEL_IID, RELATION_SPAWN_ZONE_ENTITY_IID, SELECTOR_ENTITY_BY_INTERFACE_ID_IID } from "../interfaceIds";

export const hideableInterfaceIds = [
  COLLIDER_RELATION_TAG_IID,
  SELECTOR_ENTITY_BY_INTERFACE_ID_IID,
  RELATION_SPAWN_ENTITY_MODEL_IID,
  ENTITY_SPAWN_ZONE_ENTITY_IID,
  EDIT_ENTITY_AID,
  IMPORT_DATA_SOURCE_AID,
  PLACE_ENTITY_AID,
  PROJECTILE_ENTITY_SELECTOR_IID,
]