import { COLLIDER_RELATION_TAG_IID, ENTITY_SPAWN_ZONE_ENTITY_IID, RELATION_SPAWN_ENTITY_MODEL_IID, RELATION_SPAWN_ZONE_ENTITY_IID } from "../interfaceIds";

export const hideableInterfaceIds = [
  RELATION_SPAWN_ENTITY_MODEL_IID,
  RELATION_SPAWN_ZONE_ENTITY_IID,
  COLLIDER_RELATION_TAG_IID,
  ENTITY_SPAWN_ZONE_ENTITY_IID
]