import {  MOVEMENT_CONTROLS_DOWN_IID, MOVEMENT_CONTROLS_TYPE_IID, MOVEMENT_DRAG_X_IID, MOVEMENT_DRAG_Y_IID, MOVEMENT_GRAVITY_X_IID, MOVEMENT_GRAVITY_Y_IID, MOVEMENT_IGNORE_GRAVITY_IID, MOVEMENT_PATTERN_IID, MOVEMENT_SPEED_IID, MOVEMENT_VELOCITY_X_IID, MOVEMENT_VELOCITY_Y_IID } from "../interfaceIds";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  [MOVEMENT_IGNORE_GRAVITY_IID]: {},
  [MOVEMENT_SPEED_IID]: {
    isDefaultUnlocked: true
  },
  [MOVEMENT_PATTERN_IID]: {},
  [MOVEMENT_GRAVITY_Y_IID]: {},
  [MOVEMENT_GRAVITY_X_IID]: {},
  [MOVEMENT_DRAG_Y_IID]: {},
  [MOVEMENT_DRAG_X_IID]: {},
  [MOVEMENT_VELOCITY_Y_IID]: {},
  [MOVEMENT_VELOCITY_X_IID]: {},
  [MOVEMENT_CONTROLS_TYPE_IID]: {},
  [MOVEMENT_CONTROLS_DOWN_IID]: {},
}