import { PHYSICS_BOUNCE, PHYSICS_COLLIDERS, PHYSICS_FRICTION, PHYSICS_IGNORE_BOUNDARIES, PHYSICS_IGNORE_SIDES, PHYSICS_IMMOVABLE, PHYSICS_MASS, PHYSICS_PUSHABLE } from "../interfaceIds";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  [PHYSICS_COLLIDERS]: {},
  [PHYSICS_IGNORE_SIDES]: {},
  [PHYSICS_BOUNCE]: {},
  [PHYSICS_FRICTION]: {},
  [PHYSICS_MASS]: {},
  [PHYSICS_PUSHABLE]: {},
  [PHYSICS_IMMOVABLE]: {},
  [PHYSICS_IGNORE_BOUNDARIES]: {},
}