import { RELATION_ADVANCED_CONTAINER, RELATION_ADVANCED_IGNORE_SIDES, RELATION_ADVANCED_REMOTE_EFFECTED, RELATION_DELAY_INTERVAL, RELATION_ONLY_ONCE } from "../interfaceIds";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  [RELATION_ADVANCED_CONTAINER]: {},
  [RELATION_ADVANCED_IGNORE_SIDES]: {},
  [RELATION_ADVANCED_REMOTE_EFFECTED]: {},
  [RELATION_DELAY_INTERVAL]: {},
  [RELATION_ONLY_ONCE]: {},
}