import { EFFECT_ADD_IID, EFFECT_ADVANCED_CONTAINER_IID, EFFECT_CONTAINER_IID, EFFECT_PICK_RANDOM_ZONE_IID, EFFECT_REMOTE_IID, EFFECT_SELECT_IID, EVENT_ADD_IID, EVENT_ADVANCED_CONTAINER_IID, EVENT_BOUNDARY_IID, EVENT_CONTAINER_IID, EVENT_DELAY_IID, EVENT_DELAY_INTERVAL_IID, EVENT_IGNORE_SIDES_IID, EVENT_ONLY_ONCE_IID, EVENT_SELECT_IID } from "../interfaceIds";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  [EVENT_ADVANCED_CONTAINER_IID]: {},
  [EVENT_IGNORE_SIDES_IID]: {},
  [EVENT_DELAY_INTERVAL_IID]: {}, 
  [EVENT_DELAY_IID]: {},
  [EVENT_ONLY_ONCE_IID]: {},
  [EVENT_BOUNDARY_IID]: {},

  [EFFECT_REMOTE_IID]: {},
  [EFFECT_PICK_RANDOM_ZONE_IID]: {},

  [EVENT_ADD_IID]: {}, 
  [EVENT_SELECT_IID]: {},
  [EVENT_CONTAINER_IID]: {}, 

  [EFFECT_ADD_IID]: {},
  [EFFECT_SELECT_IID]: {},
  [EFFECT_CONTAINER_IID]: {},
  [EFFECT_ADVANCED_CONTAINER_IID]: {},
}