import { RELATION_ADVANCED_CONTAINER_IID, RELATION_ADVANCED_DELAY_INTERVAL_IID, RELATION_ADVANCED_IGNORE_SIDES_IID, RELATION_ADVANCED_REMOTE_EFFECTED_IID, RELATION_BOUNDARY_IID, RELATION_DELAY_EFFECT_IID, RELATION_ONLY_ONCE_IID, RELATION_PICK_RANDOM_ZONE_IID } from "../interfaceIds";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  [RELATION_ADVANCED_CONTAINER_IID]: {},
  [RELATION_ADVANCED_IGNORE_SIDES_IID]: {},
  [RELATION_ADVANCED_REMOTE_EFFECTED_IID]: {},
  [RELATION_ADVANCED_DELAY_INTERVAL_IID]: {},
  [RELATION_ONLY_ONCE_IID]: {},
  [RELATION_DELAY_EFFECT_IID]: {},
  [RELATION_PICK_RANDOM_ZONE_IID]: {},
  [RELATION_BOUNDARY_IID]: {}
}