export const COBROWSE_SELECT_TOOL_AID = 'COBROWSE_SELECT_TOOL_AID';
export const COBROWSE_UNLOCK_TOOL_AID = 'COBROWSE_UNLOCK_TOOL_AID';
export const COBROWSE_WIGGLE_TOOL_AID = 'COBROWSE_WIGGLE_TOOL_AID';
export const COBROWSE_ACTIVE_TOGGLE_AID = 'COBROWSE_ACTIVE_TOGGLE_AID';