import { DATA_SOURCE_AUTOGENERATED, DATA_SOURCE_CORE_LIBRARY, DATA_SOURCE_GAME_MODEL, DATA_SOURCE_USER_LIBRARY } from "../core";

// autogeneated maybe can be called Preset or Created Automatically
export const dataSourceToDisplayName = {
  [DATA_SOURCE_AUTOGENERATED]: 'Autogenerated',
  [DATA_SOURCE_CORE_LIBRARY]: 'Core Library',
  [DATA_SOURCE_USER_LIBRARY]: 'User Library',
  [DATA_SOURCE_GAME_MODEL]: 'Game Model'
}

export const dataSourceToIcon = {
  [DATA_SOURCE_CORE_LIBRARY]: 'faBookAtlas',
  [DATA_SOURCE_USER_LIBRARY]: 'faBookBookmark',
  [DATA_SOURCE_AUTOGENERATED]: 'faWandMagicSparkles',
  [DATA_SOURCE_GAME_MODEL]: null,
}