import { DATA_SOURCE_AUTOGENERATED_IID, DATA_SOURCE_CORE_LIBRARY_IID, DATA_SOURCE_ENTITY_MODEL_IID, DATA_SOURCE_GAME_MODEL_IID, DATA_SOURCE_USER_LIBRARY_IID , IS_DATA_HIDDEN_IID, IS_DATA_REMOVED_IID } from "../../../constants/interfaceIds";

// autogeneated maybe can be called Preset or Created Automatically
export const dataSourceToDisplayName = {
  [DATA_SOURCE_AUTOGENERATED_IID]: 'Autogenerated',
  [DATA_SOURCE_CORE_LIBRARY_IID]: 'Core Library',
  [DATA_SOURCE_USER_LIBRARY_IID]: 'User Library',
  [DATA_SOURCE_GAME_MODEL_IID]: 'Game Model',
  [DATA_SOURCE_ENTITY_MODEL_IID]: 'Class',
  [IS_DATA_HIDDEN_IID]: 'Hidden',
  [IS_DATA_REMOVED_IID]: 'Removed',
}

export const dataSourceToIcon = {
  [DATA_SOURCE_CORE_LIBRARY_IID]: 'faBookAtlas',
  [DATA_SOURCE_USER_LIBRARY_IID]: 'faBookBookmark',
  [DATA_SOURCE_AUTOGENERATED_IID]: 'faWandMagicSparkles',
  [DATA_SOURCE_ENTITY_MODEL_IID]: 'faChessPawn',
  [IS_DATA_HIDDEN_IID]: 'faEyeSlash',
  [IS_DATA_REMOVED_IID]: 'faTrash',
  [DATA_SOURCE_GAME_MODEL_IID]: null,
}


