
import { BASIC_ENTITY_IID, NPC_ENTITY_IID,  PLAYER_ENTITY_IID, POWERUP_ENTITY_IID,ZONE_ENTITY_IID,  BASIC_ENTITY_CONTAINER_IID, NPC_ENTITY_CONTAINER_IID, PLAYER_ENTITY_CONTAINER_IID, POWERUP_ENTITY_CONTAINER_IID, ZONE_ENTITY_CONTAINER_IID } from "../../../constants/interfaceIds";
import { BASIC_ENTITY_TYPE_PREFIX, NPC_ENTITY_TYPE_PREFIX, PLAYER_ENTITY_TYPE_PREFIX, POWERUP_ENTITY_TYPE_PREFIX, ZONE_ENTITY_TYPE_PREFIX } from "../core";

export const entityModelClassToPrefix = {
  [ZONE_ENTITY_IID]: ZONE_ENTITY_TYPE_PREFIX,
  [PLAYER_ENTITY_IID]: PLAYER_ENTITY_TYPE_PREFIX,
  [BASIC_ENTITY_IID]: BASIC_ENTITY_TYPE_PREFIX,
  [NPC_ENTITY_IID]: NPC_ENTITY_TYPE_PREFIX,
  // [POWERUP_ENTITY_IID]: POWERUP_ENTITY_TYPE_PREFIX
}

export const entityModelClassToContainerIID = {
  [PLAYER_ENTITY_IID]: PLAYER_ENTITY_CONTAINER_IID,
  [BASIC_ENTITY_IID]: BASIC_ENTITY_CONTAINER_IID,
  [ZONE_ENTITY_IID]:ZONE_ENTITY_CONTAINER_IID,
  [NPC_ENTITY_IID]: NPC_ENTITY_CONTAINER_IID,
  // [POWERUP_ENTITY_IID]: POWERUP_ENTITY_CONTAINER_IID
}

export const entityModelClassToDisplayName = {
  [PLAYER_ENTITY_IID]: 'Player',
  [BASIC_ENTITY_IID]: 'Object',
  [ZONE_ENTITY_IID]: 'Zone',
  [NPC_ENTITY_IID]: 'NPC',
  // [POWERUP_ENTITY_IID]: 'Power Up',
}
  



  

  
  