import { INSTRUCTION_GAME_ROOM, INSTRUCTION_LOBBY } from "../instructions";
import { STEP_CHANGE_ACTIVITY, STEP_EFFECT, STEP_GAME_INSTANCE_EVENT, STEP_LOBBY_EVENT, STEP_OPEN_INTERFACE, STEP_UNLOCK_INTERFACE } from "../steps";

export const instructionCategoryToStepBehaviors = {
  [INSTRUCTION_GAME_ROOM]: [STEP_EFFECT, STEP_GAME_INSTANCE_EVENT, STEP_OPEN_INTERFACE, STEP_UNLOCK_INTERFACE],
  [INSTRUCTION_LOBBY]: [STEP_CHANGE_ACTIVITY, STEP_LOBBY_EVENT],
}

export const stepBehaviorToDisplayName = {
  [STEP_EFFECT]: 'Game Effect',
  [STEP_GAME_INSTANCE_EVENT]: 'Game Animation',
  [STEP_LOBBY_EVENT]: 'Lobby Animation',
  [STEP_CHANGE_ACTIVITY]: 'Change Activity',
  [STEP_OPEN_INTERFACE]: 'Open Interface',
  [STEP_UNLOCK_INTERFACE]: 'Unlock Interface',
}
