export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const LOGIN_SOCKET_LOADING = 'LOGIN_SOCKET_LOADING';
export const LOGIN_SOCKET_SUCCESS = 'LOGIN_SOCKET_SUCCESS';
export const LOGIN_SOCKET_FAIL = 'LOGIN_SOCKET_FAIL';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';

export const GET_FEATURE = 'GET_FEATURE';
export const GET_USER = 'GET_USER';

export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

export const ADD_MESSAGE_LOADING = 'ADD_MESSAGE_LOADING';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAIL = 'ADD_MESSAGE_FAIL';

export const DELETE_MESSAGE_LOADING = 'DELETE_MESSAGE_LOADING';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';

export const EDIT_MESSAGE_LOADING = 'EDIT_MESSAGE_LOADING';
export const EDIT_MESSAGE_SUCCESS = 'EDIT_MESSAGE_SUCCESS';
export const EDIT_MESSAGE_FAIL = 'EDIT_MESSAGE_FAIL';
export const CLEAR_MESSAGE_ERROR = 'CLEAR_MESSAGE_ERROR';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_LOBBYS_LOADING = 'GET_LOBBYS_LOADING';
export const GET_LOBBYS_SUCCESS = 'GET_LOBBYS_SUCCESS';
export const GET_LOBBYS_FAIL = 'GET_LOBBYS_FAIL';

export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const JOIN_LOBBY_LOADING = 'JOIN_LOBBY_LOADING';
export const JOIN_LOBBY_SUCCESS = 'JOIN_LOBBY_SUCCESS';
export const JOIN_LOBBY_FAIL = 'JOIN_LOBBY_FAIL';

export const LEAVE_LOBBY_LOADING = 'LEAVE_LOBBY_LOADING';
export const LEAVE_LOBBY_SUCCESS = 'LEAVE_LOBBY_SUCCESS';
export const LEAVE_LOBBY_FAIL = 'LEAVE_LOBBY_FAIL';

export const ADD_LOBBY_LOADING = 'ADD_LOBBY_LOADING';
export const ADD_LOBBY_SUCCESS = 'ADD_LOBBY_SUCCESS';
export const ADD_LOBBY_FAIL = 'ADD_LOBBY_FAIL';

export const GET_LOBBY_LOADING = 'GET_LOBBY_LOADING';
export const GET_LOBBY_SUCCESS = 'GET_LOBBY_SUCCESS';
export const GET_LOBBY_FAIL = 'GET_LOBBY_FAIL';

export const EDIT_LOBBY_LOADING = 'EDIT_LOBBY_LOADING';
export const EDIT_LOBBY_SUCCESS = 'EDIT_LOBBY_SUCCESS';
export const EDIT_LOBBY_FAIL = 'EDIT_LOBBY_FAIL';

export const DELETE_LOBBY_LOADING = 'DELETE_LOBBY_LOADING';
export const DELETE_LOBBY_SUCCESS = 'DELETE_LOBBY_SUCCESS';
export const DELETE_LOBBY_FAIL = 'DELETE_LOBBY_FAIL';

export const RESEED_DATABASE_LOADING = 'RESEED_DATABASE_LOADING';
export const RESEED_DATABASE_SUCCESS = 'RESEED_DATABASE_SUCCESS';
export const RESEED_DATABASE_FAIL = 'RESEED_DATABASE_FAIL';
