// AUTH
export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const AUTHENTICATE_SOCKET_LOADING = 'AUTHENTICATE_SOCKET_LOADING';
export const AUTHENTICATE_SOCKET_SUCCESS = 'AUTHENTICATE_SOCKET_SUCCESS';
export const AUTHENTICATE_SOCKET_FAIL = 'AUTHENTICATE_SOCKET_FAIL';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';

export const CLEAR_REDIRECT = 'CLEAR_REDIRECT'
export const SET_REDIRECT = 'SET_REDIRECT'

export const ON_SOCKET_CONNECT = 'connect';
export const ON_SOCKET_DISCONNECT = 'ON_SOCKET_DISCONNECT';

export const GET_USER = 'GET_USER';


// MESSSAGES
export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

export const ADD_MESSAGE_LOADING = 'ADD_MESSAGE_LOADING';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAIL = 'ADD_MESSAGE_FAIL';

export const DELETE_MESSAGE_LOADING = 'DELETE_MESSAGE_LOADING';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';

export const EDIT_MESSAGE_LOADING = 'EDIT_MESSAGE_LOADING';
export const EDIT_MESSAGE_SUCCESS = 'EDIT_MESSAGE_SUCCESS';
export const EDIT_MESSAGE_FAIL = 'EDIT_MESSAGE_FAIL';
export const CLEAR_MESSAGE_ERROR = 'CLEAR_MESSAGE_ERROR';


// USERS
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const ADD_USER_SPEED_TEST_LOADING = 'ADD_USER_SPEED_TEST_LOADING';
export const ADD_USER_SPEED_TEST_SUCCESS = 'ADD_USER_SPEED_TEST_SUCCESS';
export const ADD_USER_SPEED_TEST_FAIL = 'ADD_USER_SPEED_TEST_FAIL';

export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// LOBBYS
export const GET_LOBBYS_LOADING = 'GET_LOBBYS_LOADING';
export const GET_LOBBYS_SUCCESS = 'GET_LOBBYS_SUCCESS';
export const GET_LOBBYS_FAIL = 'GET_LOBBYS_FAIL';

export const JOIN_LOBBY_LOADING = 'JOIN_LOBBY_LOADING';
export const JOIN_LOBBY_SUCCESS = 'JOIN_LOBBY_SUCCESS';
export const JOIN_LOBBY_FAIL = 'JOIN_LOBBY_FAIL';

export const SEND_LOBBY_MESSAGE_LOADING = 'SEND_LOBBY_MESSAGE_LOADING';
export const SEND_LOBBY_MESSAGE_SUCCESS = 'SEND_LOBBY_MESSAGE_SUCCESS';
export const SEND_LOBBY_MESSAGE_FAIL = 'SEND_LOBBY_MESSAGE_FAIL';

export const LEAVE_LOBBY_LOADING = 'LEAVE_LOBBY_LOADING';
export const LEAVE_LOBBY_SUCCESS = 'LEAVE_LOBBY_SUCCESS';
export const LEAVE_LOBBY_FAIL = 'LEAVE_LOBBY_FAIL';

export const ASSIGN_LOBBY_ROLE_LOADING = 'ASSIGN_LOBBY_ROLE_LOADING';
export const ASSIGN_LOBBY_ROLE_SUCCESS = 'ASSIGN_LOBBY_ROLE_SUCCESS';
export const ASSIGN_LOBBY_ROLE_FAIL = 'ASSIGN_LOBBY_ROLE_FAIL';




export const ADD_LOBBY_LOADING = 'ADD_LOBBY_LOADING';
export const ADD_LOBBY_SUCCESS = 'ADD_LOBBY_SUCCESS';
export const ADD_LOBBY_FAIL = 'ADD_LOBBY_FAIL';

export const LOBBY_UNDO_LOADING = 'LOBBY_UNDO_LOADING';
export const LOBBY_UNDO_SUCCESS = 'LOBBY_UNDO_SUCCESS';
export const LOBBY_UNDO_FAIL = 'LOBBY_UNDO_FAIL';

export const GET_LOBBY_LOADING = 'GET_LOBBY_LOADING';
export const GET_LOBBY_SUCCESS = 'GET_LOBBY_SUCCESS';
export const GET_LOBBY_FAIL = 'GET_LOBBY_FAIL';

export const EDIT_LOBBY_LOADING = 'EDIT_LOBBY_LOADING';
export const EDIT_LOBBY_SUCCESS = 'EDIT_LOBBY_SUCCESS';
export const EDIT_LOBBY_FAIL = 'EDIT_LOBBY_FAIL';

export const UPDATE_LOBBY_USER_LOADING = 'UPDATE_LOBBY_USER_LOADING';
export const UPDATE_LOBBY_USER_SUCCESS = 'UPDATE_LOBBY_USER_SUCCESS';
export const UPDATE_LOBBY_USER_FAIL = 'UPDATE_LOBBY_USER_FAIL';

export const DELETE_LOBBY_LOADING = 'DELETE_LOBBY_LOADING';
export const DELETE_LOBBY_SUCCESS = 'DELETE_LOBBY_SUCCESS';
export const DELETE_LOBBY_FAIL = 'DELETE_LOBBY_FAIL';

export const RESEED_DATABASE_LOADING = 'RESEED_DATABASE_LOADING';
export const RESEED_DATABASE_SUCCESS = 'RESEED_DATABASE_SUCCESS';
export const RESEED_DATABASE_FAIL = 'RESEED_DATABASE_FAIL';

export const START_VIDEO_CALL_LOADING = 'START_VIDEO_CALL_LOADING';
export const START_VIDEO_CALL_SUCCESS = 'START_VIDEO_CALL_SUCCESS';
export const START_VIDEO_CALL_FAIL = 'START_VIDEO_CALL_FAIL';
export const LEAVE_VIDEO_CALL_SUCCESS = 'LEAVE_VIDEO_CALL_SUCCESS';
export const LEAVE_VIDEO_CALL_FAIL = 'LEAVE_VIDEO_CALL_FAIL';
export const BYPASS_VIDEO_CALL = 'BYPASS_VIDEO_CALL';
export const SET_VIDEO_TRACK_COMPONENT = 'SET_VIDEO_TRACK_COMPONENT';


export const SET_CUT_VIDEO = 'SET_CUT_VIDEO';
export const SET_CUT_AUDIO = 'SET_CUT_AUDIO';


export const UPDATE_ONBOARDING_STEP = 'UPDATE_ONBOARDING_STEP';

export const SET_VIDEO_TRACK_ID = 'SET_VIDEO_TRACK_ID';
export const SET_AUDIO_TRACK_ID = 'SET_AUDIO_TRACK_ID';

export const GET_ARCADE_GAMES_LOADING = 'GET_ARCADE_GAMES_LOADING';
export const GET_ARCADE_GAMES_SUCCESS = 'GET_ARCADE_GAMES_SUCCESS';
export const GET_ARCADE_GAMES_FAIL = 'GET_ARCADE_GAMES_FAIL';

export const GET_ARCADE_GAME_LOADING = 'GET_ARCADE_GAME_LOADING';
export const GET_ARCADE_GAME_SUCCESS = 'GET_ARCADE_GAME_SUCCESS';
export const GET_ARCADE_GAME_FAIL = 'GET_ARCADE_GAME_FAIL';


export const MARK_TEXTURE_STROKES_PENDING = 'MARK_TEXTURE_STROKES_PENDING';
export const MARK_TEXTURE_UNSAVED = 'MARK_TEXTURE_UNSAVED';
export const SAVE_TEXTURE_LOADING = 'SAVE_TEXTURE_LOADING';
export const SAVE_TEXTURE_SUCCESS = 'SAVE_TEXTURE_SUCCESS';
export const SAVE_TEXTURE_FAIL = 'SAVE_TEXTURE_FAIL';

export const LOAD_GAME_MODEL_LOADING = 'LOAD_GAME_MODEL_LOADING';
export const LOAD_GAME_MODEL_SUCCESS = 'LOAD_GAME_MODEL_SUCCESS';
export const LOAD_GAME_MODEL_FAIL = 'LOAD_GAME_MODEL_FAIL';

export const EDIT_GAME_MODEL_LOADING = 'EDIT_GAME_MODEL_LOADING'
export const EDIT_GAME_MODEL_FAIL = 'EDIT_GAME_MODEL_FAIL'

export const ADD_ARCADE_GAME_LOADING = 'ADD_ARCADE_GAME_LOADING';
export const ADD_ARCADE_GAME_SUCCESS = 'ADD_ARCADE_GAME_SUCCESS';
export const ADD_ARCADE_GAME_FAIL = 'ADD_ARCADE_GAME_FAIL';

export const EDIT_ARCADE_GAME_LOADING = 'EDIT_ARCADE_GAME_LOADING';
export const EDIT_ARCADE_GAME_SUCCESS = 'EDIT_ARCADE_GAME_SUCCESS';
export const EDIT_ARCADE_GAME_FAIL = 'EDIT_ARCADE_GAME_FAIL';

export const UNLOAD_GAME_MODEL = 'UNLOAD_GAME_MODEL';
export const SET_GAME_INSTANCE = 'SET_GAME_INSTANCE';

export const SET_SPRITE_EDITOR_GAME_INSTANCE = 'SET_SPRITE_EDITOR_GAME_INSTANCE';

export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';

export const OPEN_SELECT_BACKGROUND_COLOR = 'OPEN_SELECT_BACKGROUND_COLOR';
export const CLOSE_SELECT_BACKGROUND_COLOR = 'CLOSE_SELECT_BACKGROUND_COLOR';

export const OPEN_SELECT_AGGREGATE_COLOR = 'OPEN_SELECT_AGGREGATE_COLOR';
export const CLOSE_SELECT_AGGREGATE_COLOR = 'CLOSE_SELECT_AGGREGATE_COLOR';

export const OPEN_JSON_VIEWER = 'OPEN_JSON_VIEWER';
export const CLOSE_JSON_VIEWER = 'CLOSE_JSON_VIEWER';

export const OPEN_LIVE_EDITOR = 'OPEN_LIVE_EDITOR';
export const OPEN_SECTION_EDITOR = 'OPEN_SECTION_EDITOR';
export const CLOSE_LIVE_EDITOR = 'CLOSE_LIVE_EDITOR';
export const CLOSE_SECTION_EDITOR = 'CLOSE_SECTION_EDITOR';
export const CHANGE_EDITOR_CAMERA_ZOOM = 'CHANGE_EDITOR_CAMERA_ZOOM';

export const SELECT_CLASS = 'SELECT_CLASS';
export const CLEAR_CLASS = 'CLEAR_CLASS';

export const SELECT_BRUSH = 'SELECT_BRUSH';
export const CLEAR_BRUSH = 'CLEAR_BRUSH';

export const GET_SPRITESHEET_DATA_LOADING = 'GET_SPRITESHEET_DATA_LOADING'
export const GET_SPRITESHEET_DATA_SUCCESS = 'GET_SPRITESHEET_DATA_SUCCESS'
export const GET_SPRITESHEET_DATA_FAIL = 'GET_SPRITESHEET_DATA_FAIL'

export const CLEAR_EDITOR_FORMS = 'CLEAR_EDITOR_FORMS'
export const CLEAR_EDITOR = 'CLEAR_EDITOR'
export const CLEAR_GAME_VIEW_EDITOR = 'CLEAR_GAME_VIEW_EDITOR'

export const TOGGLE_COBROWSING = 'TOGGLE_COBROWSING'
export const TOGGLE_UNLOCKABLE_INTERFACE_LOCKS = 'TOGGLE_UNLOCKABLE_INTERFACE_LOCKS'

export const TOGGLE_GRID_VIEW = 'TOGGLE_GRID_VIEW'

export const CHANGE_CLASS_ID_HOVERING = 'CHANGE_CLASS_ID_HOVERING'
export const CHANGE_BRUSH_ID_HOVERING = 'CHANGE_BRUSH_ID_HOVERING'
export const CHANGE_INSTANCE_HOVERING = 'CHANGE_INSTANCE_HOVERING'

export const TOGGLE_CANVAS_VISIBILITY = 'TOGGLE_CANVAS_VISIBILITY'
export const TOGGLE_GAME_INSTANCE_PAUSED = 'TOGGLE_GAME_INSTANCE_PAUSED'

export const OPEN_SNAPSHOT_TAKER = 'OPEN_SNAPSHOT_TAKER'
export const CLOSE_SNAPSHOT_TAKER = 'CLOSE_SNAPSHOT_TAKER'

export const OPEN_GAME_METADATA_MODAL = 'OPEN_GAME_METADATA_MODAL'
export const CLOSE_GAME_METADATA_MODAL = 'CLOSE_GAME_METADATA_MODAL'

export const OPEN_CLASS_BOX_MODAL = 'OPEN_CLASS_BOX_MODAL'
export const CLOSE_CLASS_BOX_MODAL = 'CLOSE_CLASS_BOX_MODAL'

export const OPEN_SETUP_CHOICES_MODAL = 'OPEN_SETUP_CHOICES_MODAL'
export const CLOSE_SETUP_CHOICES_MODAL = 'CLOSE_SETUP_CHOICES_MODAL'

export const OPEN_CLASS_NAME_MODAL = 'OPEN_CLASS_NAME_MODAL'
export const CLOSE_CLASS_NAME_MODAL = 'CLOSE_CLASS_NAME_MODAL'

export const OPEN_CREATE_CLASS_FLOW = 'OPEN_CREATE_CLASS_FLOW'
export const CLOSE_CREATE_CLASS_FLOW = 'CLOSE_CREATE_CLASS_FLOW'
export const UPDATE_CREATE_CLASS = 'UPDATE_CREATE_CLASS'

export const OPEN_CREATE_CUTSCENE = 'OPEN_CREATE_CUTSCENE'
export const CLOSE_CREATE_CUTSCENE = 'CLOSE_CREATE_CUTSCENE'
export const UPDATE_CREATE_CUTSCENE = 'UPDATE_CREATE_CUTSCENE'

export const OPEN_CUTSCENES_MENU = 'OPEN_CUTSCENES_MENU'
export const CLOSE_CUTSCENES_MENU = 'CLOSE_CUTSCENES_MENU'

export const OPEN_CREATE_STAGE = 'OPEN_CREATE_STAGE'
export const CLOSE_CREATE_STAGE = 'CLOSE_CREATE_STAGE'
export const UPDATE_CREATE_STAGE = 'UPDATE_CREATE_STAGE'

export const OPEN_STAGES_MENU = 'OPEN_STAGES_MENU'
export const CLOSE_STAGES_MENU = 'CLOSE_STAGES_MENU'

export const OPEN_CREATE_RELATION = 'OPEN_CREATE_RELATION'
export const CLOSE_CREATE_RELATION = 'CLOSE_CREATE_RELATION'
export const UPDATE_CREATE_RELATION = 'UPDATE_CREATE_RELATION'

export const OPEN_BOUNDARY_RELATION = 'OPEN_BOUNDARY_RELATION'
export const CLOSE_BOUNDARY_RELATION = 'CLOSE_BOUNDARY_RELATION'
export const UPDATE_BOUNDARY_RELATION = 'UPDATE_BOUNDARY_RELATION'

export const OPEN_RELATIONS_MENU = 'OPEN_RELATIONS_MENU'
export const CLOSE_RELATIONS_MENU = 'CLOSE_RELATIONS_MENU'

export const OPEN_SPRITE_EDITOR = 'OPEN_SPRITE_EDITOR'
export const CLOSE_SPRITE_EDITOR = 'CLOSE_SPRITE_EDITOR'

export const OPEN_CREATE_BRUSH_FLOW = 'OPEN_CREATE_BRUSH_FLOW'
export const UPDATE_CREATE_BRUSH = 'UPDATE_CREATE_BRUSH'
export const CLOSE_CREATE_BRUSH_FLOW = 'CLOSE_CREATE_BRUSH_FLOW'
export const UPDATE_CREATE_BRUSH_STEP = 'UPDATE_CREATE_BRUSH_STEP'

export const UPDATE_ACCORDIAN_LIST = 'UPDATE_ACCORDIAN_LIST'
export const UPDATE_VERTICAL_LINEAR_STEPPER = 'UPDATE_VERTICAL_LINEAR_STEPPER'

export const OPEN_CREATE_COLOR_FLOW = 'OPEN_CREATE_COLOR_FLOW'
export const TOGGLE_EYE_DROPPER = 'TOGGLE_EYE_DROPPER'
export const CLOSE_CREATE_COLOR_FLOW = 'CLOSE_CREATE_COLOR_FLOW'

export const UPDATE_BRUSH_SIZE = 'UPDATE_BRUSH_SIZE'

export const LOCK_INTERFACE = 'LOCK_INTERFACE';
export const UNLOCK_INTERFACE = 'UNLOCK_INTERFACE';

export const OPEN_INTERFACE_TREE = 'OPEN_INTERFACE_TREE';
export const CLOSE_INTERFACE_TREE = 'CLOSE_INTERFACE_TREE';


export const UNDO_INSTANCE_CHANGE_SUCCESS = 'UNDO_INSTANCE_CHANGE_SUCCES'
export const UNDO_INSTANCE_CHANGE_FAIL = 'UNDO_INSTANCE_CHANGE_FAIL'


export const ON_AUTHENTICATE_SOCKET_SUCCESS = 'ON_AUTHENTICATE_SOCKET_SUCCESS';
export const ON_AUTHENTICATE_SOCKET_FAIL = 'ON_AUTHENTICATE_SOCKET_FAIL';

export const ON_GAME_ROOM_UPDATE = 'ON_GAME_ROOM_UPDATE';

export const ON_GAME_CHARACTER_UPDATE = 'ON_GAME_CHARACTER_UPDATE';
export const ON_GAME_INSTANCE_EVENT = 'ON_GAME_INSTANCE_EVENT';
export const ON_GAME_INSTANCE_UPDATE = 'ON_GAME_INSTANCE_UPDATE';
export const ON_GAME_INSTANCE_UPDATE_ACKNOWLEDGED = 'ON_GAME_INSTANCE_UPDATE_ACKNOWLEDGED';
export const ON_GAME_MODEL_UPDATE = 'ON_GAME_MODEL_UPDATE';
export const CHANGE_PLAYER_STATE = 'CHANGE_PLAYER_STATE';
export const CHANGE_PLAYER_CLASS = 'CHANGE_PLAYER_CLASS';

export const CHANGE_CURRENT_STAGE = 'CHANGE_CURRENT_STAGE';
export const CHANGE_CONTROL_POPUP = 'CHANGE_CONTROL_POPUP';

export const SET_MOUSE_OVER_INTERFACE_ID = 'SET_MOUSE_OVER_INTERFACE_ID'
export const SELECT_COBROWSING_TOOL = 'SELECT_COBROWSING_TOOL'

export const ON_LOBBY_UNDO = 'ON_LOBBY_UNDO';
export const ON_LOBBY_UPDATE = 'ON_LOBBY_UPDATE';
export const ON_LOBBY_USER_STATUS_UPDATE = 'ON_LOBBY_USER_STATUS_UPDATE';
// export const ON_LOBBY_SEND_MESSAGE = 'ON_LOBBY_SEND_MESSAGE';

export const OPEN_MY_SPRITES_MODAL = 'OPEN_MY_SPRITES_MODAL';
export const CLOSE_MY_SPRITES_MODAL = 'CLOSE_MY_SPRITES_MODAL';


// COBROWSING 
export const INITIALIZE_UNLOCKABLE_INTERFACE_IDS = 'INITIALIZE_UNLOCKABLE_INTERFACE_IDS'
export const INITIALIZE_COBROWSING_STATE = 'INITIALIZE_COBROWSING_STATE';

export const ON_COBROWSING_UPDATE = 'ON_COBROWSING_UPDATE';
export const ON_COBROWSING_STATUS_UPDATE = 'ON_COBROWSING_STATUS_UPDATE';
export const ON_COBROWSING_SUBSCRIBED = 'ON_COBROWSING_SUBSCRIBED';
export const ON_COBROWSING_REMOTE_DISPATCH = 'ON_COBROWSING_REMOTE_DISPATCH';
export const ON_CLEAR_COBROWSING_STATUS = 'ON_CLEAR_COBROWSING_STATUS';

export const START_COBROWSING_SUCCESS = 'PUBLISH_COBROWSING_SUCCESS';
export const START_COBROWSING_FAIL = 'PUBLISH_COBROWSING_FAIL';

export const END_COBROWSING_SUCCESS = 'END_COBROWSING_SUCCESS';
export const END_COBROWSING_FAIL = 'END_COBROWSING_FAIL';

export const UPDATE_COBROWSING_FAIL = 'UPDATE_COBROWSING_FAIL'

export const SUBSCRIBE_COBROWSING_LOADING = 'SUBSCRIBE_COBROWSING_LOADING';
export const SUBSCRIBE_COBROWSING_SUCCESS = 'SUBSCRIBE_COBROWSING_SUCCESS';
export const SUBSCRIBE_COBROWSING_FAIL = 'SUBSCRIBE_COBROWSING_FAIL';

export const UNSUBSCRIBE_COBROWSING_LOADING = 'UNSUBSCRIBE_COBROWSING_LOADING';
export const UNSUBSCRIBE_COBROWSING_SUCCESS = 'UNSUBSCRIBE_COBROWSING_SUCCESS';
export const UNSUBSCRIBE_COBROWSING_FAIL = 'UNSUBSCRIBE_COBROWSING_FAIL';

// CUTSCENES

export const OPEN_CUTSCENE = 'OPEN_CUTSCENE';
export const PROGRESS_CUTSCENE = 'PROGRESS_CUTSCENE';
export const CLOSE_CUTSCENE = 'CLOSE_CUTSCENE';

// CONSTELLATION
export const START_OPEN_CONSTELLATION = 'START_OPEN_CONSTELLATION';
export const OPEN_CONSTELLATION = 'OPEN_CONSTELLATION';
export const START_CLOSE_CONSTELLATION = 'START_CLOSE_CONSTELLATION';
export const COMPLETE_CLOSE_CONSTELLATION = 'COMPLETE_CLOSE_CONSTELLATION';
export const CLEAR_CUTSCENES = 'CLEAR_CUTSCENES';


// ERROR

export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CHANGE_ERROR_STATE = 'CHANGE_ERROR_STATE';
export const CLEAR_ERROR_STATE = 'CLEAR_ERROR_STATE';
export const SET_RECENTLY_FOCUSED = 'SET_RECENTLY_FOCUSED'

// Snackbar
export const CLEAR_SNACKBAR = 'CLEAR_SNACKBAR';
export const ADD_SNACKBAR = 'ADD_SNACKBAR';

/// PORTFOLIO
export const PAUSE_BACKGROUND_MUSIC = 'PAUSE_BACKGROUND_MUSIC'
export const UNPAUSE_BACKGROUND_MUSIC = 'UNPAUSE_BACKGROUND_MUSIC'
export const PLAY_BACKGROUND_MUSIC = 'PLAY_BACKGROUND_MUSIC'
export const MUTE_VIDEO_AUDIO = 'MUTE_VIDEO_AUDIO'
export const UNMUTE_VIDEO_AUDIO = 'UNMUTE_VIDEO_AUDIO'


// TICKETING

export const GET_TICKETED_EVENTS_LOADING = 'GET_TICKETED_EVENTS_LOADING';
export const GET_TICKETED_EVENTS_SUCCESS = 'GET_TICKETED_EVENTS_SUCCESS';
export const GET_TICKETED_EVENTS_FAIL = 'GET_TICKETED_EVENTS_FAIL';

export const GET_TICKETED_EVENT_LOADING = 'GET_TICKETED_EVENT_LOADING';
export const GET_TICKETED_EVENT_SUCCESS = 'GET_TICKETED_EVENT_SUCCESS';
export const GET_TICKETED_EVENT_FAIL = 'GET_TICKETED_EVENT_FAIL';

export const ADD_TICKETED_EVENT_LOADING = 'ADD_TICKETED_EVENT_LOADING';
export const ADD_TICKETED_EVENT_SUCCESS = 'ADD_TICKETED_EVENT_SUCCESS';
export const ADD_TICKETED_EVENT_FAIL = 'ADD_TICKETED_EVENT_FAIL';

export const EDIT_TICKETED_EVENT_LOADING = 'EDIT_TICKETED_EVENT_LOADING';
export const EDIT_TICKETED_EVENT_SUCCESS = 'EDIT_TICKETED_EVENT_SUCCESS';
export const EDIT_TICKETED_EVENT_FAIL = 'EDIT_TICKETED_EVENT_FAIL';

export const DELETE_TICKETED_EVENT_LOADING = 'DELETE_TICKETED_EVENT_LOADING';
export const DELETE_TICKETED_EVENT_SUCCESS = 'DELETE_TICKETED_EVENT_SUCCESS';
export const DELETE_TICKETED_EVENT_FAIL = 'DELETE_TICKETED_EVENT_FAIL';


/// TICKET PURCHASES
export const UPDATE_TICKET_CART = 'UPDATE_TICKET_CART';
export const CLEAR_TICKET_CART = 'CLEAR_TICKET_CART';

// export const GET_TICKET_PURCHASES_LOADING = 'GET_TICKET_PURCHASES_LOADING';
// export const GET_TICKET_PURCHASES_SUCCESS = 'GET_TICKET_PURCHASES_SUCCESS';
// export const GET_TICKET_PURCHASES_FAIL = 'GET_TICKET_PURCHASES_FAIL';

export const GET_TICKET_PURCHASES_BY_EVENT_LOADING = 'GET_TICKET_PURCHASES_BY_EVENT_LOADING';
export const GET_TICKET_PURCHASES_BY_EVENT_SUCCESS = 'GET_TICKET_PURCHASES_BY_EVENT_SUCCESS';
export const GET_TICKET_PURCHASES_BY_EVENT_FAIL = 'GET_TICKET_PURCHASES_BY_EVENT_FAIL';

// export const GET_TICKET_PURCHASE_LOADING = 'GET_TICKET_PURCHASE_LOADING';
// export const GET_TICKET_PURCHASE_SUCCESS = 'GET_TICKET_PURCHASE_SUCCESS';
// export const GET_TICKET_PURCHASE_FAIL = 'GET_TICKET_PURCHASE_FAIL';

// export const ADD_TICKET_PURCHASE_LOADING = 'ADD_TICKET_PURCHASE_LOADING';
// export const ADD_TICKET_PURCHASE_SUCCESS = 'ADD_TICKET_PURCHASE_SUCCESS';
// export const ADD_TICKET_PURCHASE_FAIL = 'ADD_TICKET_PURCHASE_FAIL';

// export const EDIT_TICKET_PURCHASE_LOADING = 'EDIT_TICKET_PURCHASE_LOADING';
// export const EDIT_TICKET_PURCHASE_SUCCESS = 'EDIT_TICKET_PURCHASE_SUCCESS';
// export const EDIT_TICKET_PURCHASE_FAIL = 'EDIT_TICKET_PURCHASE_FAIL';

// export const DELETE_TICKET_PURCHASE_LOADING = 'DELETE_TICKET_PURCHASE_LOADING';
// export const DELETE_TICKET_PURCHASE_SUCCESS = 'DELETE_TICKET_PURCHASE_SUCCESS';
// export const DELETE_TICKET_PURCHASE_FAIL = 'DELETE_TICKET_PURCHASE_FAIL';


// INTERFACE PRESETS
export const GET_TEXTURES_LOADING = 'GET_TEXTURES_LOADING';
export const GET_TEXTURES_SUCCESS = 'GET_TEXTURES_SUCCESS';
export const GET_TEXTURES_FAIL = 'GET_TEXTURES_FAIL';

export const GET_TEXTURE_LOADING = 'GET_TEXTURE_LOADING';
export const GET_TEXTURE_SUCCESS = 'GET_TEXTURE_SUCCESS';
export const GET_TEXTURE_FAIL = 'GET_TEXTURE_FAIL';

export const ADD_TEXTURE_LOADING = 'ADD_TEXTURE_LOADING';
export const ADD_TEXTURE_SUCCESS = 'ADD_TEXTURE_SUCCESS';
export const ADD_TEXTURE_FAIL = 'ADD_TEXTURE_FAIL';

export const EDIT_TEXTURE_LOADING = 'EDIT_TEXTURE_LOADING';
export const EDIT_TEXTURE_SUCCESS = 'EDIT_TEXTURE_SUCCESS';
export const EDIT_TEXTURE_FAIL = 'EDIT_TEXTURE_FAIL';

export const DELETE_TEXTURE_LOADING = 'DELETE_TEXTURE_LOADING';
export const DELETE_TEXTURE_SUCCESS = 'DELETE_TEXTURE_SUCCESS';
export const DELETE_TEXTURE_FAIL = 'DELETE_TEXTURE_FAIL';


// INTERFACE PRESETS
export const GET_INTERFACE_PRESETS_LOADING = 'GET_INTERFACE_PRESETS_LOADING';
export const GET_INTERFACE_PRESETS_SUCCESS = 'GET_INTERFACE_PRESETS_SUCCESS';
export const GET_INTERFACE_PRESETS_FAIL = 'GET_INTERFACE_PRESETS_FAIL';

export const GET_INTERFACE_PRESET_LOADING = 'GET_INTERFACE_PRESET_LOADING';
export const GET_INTERFACE_PRESET_SUCCESS = 'GET_INTERFACE_PRESET_SUCCESS';
export const GET_INTERFACE_PRESET_FAIL = 'GET_INTERFACE_PRESET_FAIL';

export const ADD_INTERFACE_PRESET_LOADING = 'ADD_INTERFACE_PRESET_LOADING';
export const ADD_INTERFACE_PRESET_SUCCESS = 'ADD_INTERFACE_PRESET_SUCCESS';
export const ADD_INTERFACE_PRESET_FAIL = 'ADD_INTERFACE_PRESET_FAIL';

export const EDIT_INTERFACE_PRESET_LOADING = 'EDIT_INTERFACE_PRESET_LOADING';
export const EDIT_INTERFACE_PRESET_SUCCESS = 'EDIT_INTERFACE_PRESET_SUCCESS';
export const EDIT_INTERFACE_PRESET_FAIL = 'EDIT_INTERFACE_PRESET_FAIL';

export const DELETE_INTERFACE_PRESET_LOADING = 'DELETE_INTERFACE_PRESET_LOADING';
export const DELETE_INTERFACE_PRESET_SUCCESS = 'DELETE_INTERFACE_PRESET_SUCCESS';
export const DELETE_INTERFACE_PRESET_FAIL = 'DELETE_INTERFACE_PRESET_FAIL';


// EXPERIENCE PRESENTS
export const GET_ACTIVITYS_LOADING = 'GET_ACTIVITYS_LOADING';
export const GET_ACTIVITYS_SUCCESS = 'GET_ACTIVITYS_SUCCESS';
export const GET_ACTIVITYS_FAIL = 'GET_ACTIVITYS_FAIL';

export const GET_EXPERIENCE_LOADING = 'GET_EXPERIENCE_LOADING';
export const GET_EXPERIENCE_SUCCESS = 'GET_EXPERIENCE_SUCCESS';
export const GET_EXPERIENCE_FAIL = 'GET_EXPERIENCE_FAIL';

export const ADD_EXPERIENCE_LOADING = 'ADD_EXPERIENCE_LOADING';
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';
export const ADD_EXPERIENCE_FAIL = 'ADD_EXPERIENCE_FAIL';

export const EDIT_EXPERIENCE_LOADING = 'EDIT_EXPERIENCE_LOADING';
export const EDIT_EXPERIENCE_SUCCESS = 'EDIT_EXPERIENCE_SUCCESS';
export const EDIT_EXPERIENCE_FAIL = 'EDIT_EXPERIENCE_FAIL';

export const DELETE_EXPERIENCE_LOADING = 'DELETE_EXPERIENCE_LOADING';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL';


/// CODRAWINGS

export const UNDO_CODRAWING_CHANGE_SUCCESS = 'UNDO_CODRAWING_CHANGE_SUCCES'
export const UNDO_CODRAWING_CHANGE_FAIL = 'UNDO_CODRAWING_CHANGE_FAIL'

export const ON_CODRAWING_STROKE = 'ON_CODRAWING_STROKE'
export const ON_CODRAWING_SUBSCRIBED = 'ON_CODRAWING_SUBSCRIBED'
export const ON_CODRAWING_UNDO = 'ON_CODRAWING_UNDO';
export const ON_CODRAWING_STROKE_ACKNOWLEDGED = 'ON_CODRAWING_STROKE_ACKNOWLEDGED'
export const ON_CODRAWING_INITIALIZE = 'ON_CODRAWING_INITIALIZE'

export const CODRAWING_STROKE_FAILED = 'CODRAWING_STROKE_FAILED'
export const CODRAWING_UNDO_LOADING = 'CODRAWING_UNDO_LOADING';
export const CODRAWING_UNDO_SUCCESS = 'CODRAWING_UNDO_SUCCESS';
export const CODRAWING_UNDO_FAIL = 'CODRAWING_UNDO_FAIL';

export const SUBSCRIBE_CODRAWING_LOADING = 'SUBSCRIBE_CODRAWING_LOADING'
export const SUBSCRIBE_CODRAWING_SUCCESS = 'SUBSCRIBE_CODRAWING_SUCCES'
export const SUBSCRIBE_CODRAWING_FAIL = 'SUBSCRIBE_CODRAWING_FAIL'
export const UNSUBSCRIBE_CODRAWING_SUCCESS = 'UNSUBSCRIBE_CODRAWING_SUCCES'
export const UNSUBSCRIBE_CODRAWING_FAIL = 'UNSUBSCRIBE_CODRAWING_FAIL'

// THEME
export const UPDATE_THEME = 'UPDATE_THEME'


// GAME SESSION
export const ADD_GAME_ROOM_LOADING = 'ADD_GAME_ROOM_LOADING';
export const ADD_GAME_ROOM_SUCCESS = 'ADD_GAME_ROOM_SUCCESS';
export const ADD_GAME_ROOM_FAIL = 'ADD_GAME_ROOM_FAIL';

export const GAME_ROOM_UNDO_LOADING = 'GAME_ROOM_UNDO_LOADING';
export const GAME_ROOM_UNDO_SUCCESS = 'GAME_ROOM_UNDO_SUCCESS';
export const GAME_ROOM_UNDO_FAIL = 'GAME_ROOM_UNDO_FAIL';

export const GET_GAME_ROOM_LOADING = 'GET_GAME_ROOM_LOADING';
export const GET_GAME_ROOM_SUCCESS = 'GET_GAME_ROOM_SUCCESS';
export const GET_GAME_ROOM_FAIL = 'GET_GAME_ROOM_FAIL';

export const SEND_GAME_ROOM_MESSAGE_LOADING = 'SEND_GAME_ROOM_MESSAGE_LOADING';
export const SEND_GAME_ROOM_MESSAGE_SUCCESS = 'SEND_GAME_ROOM_MESSAGE_SUCCESS';
export const SEND_GAME_ROOM_MESSAGE_FAIL = 'SEND_GAME_ROOM_MESSAGE_FAIL';

export const EDIT_GAME_ROOM_LOADING = 'EDIT_GAME_ROOM_LOADING';
export const EDIT_GAME_ROOM_SUCCESS = 'EDIT_GAME_ROOM_SUCCESS';
export const EDIT_GAME_ROOM_FAIL = 'EDIT_GAME_ROOM_FAIL';

export const UPDATE_GAME_ROOM_USER_LOADING = 'UPDATE_GAME_ROOM_USER_LOADING';
export const UPDATE_GAME_ROOM_USER_SUCCESS = 'UPDATE_GAME_ROOM_USER_SUCCESS';
export const UPDATE_GAME_ROOM_USER_FAIL = 'UPDATE_GAME_ROOM_USER_FAIL';

export const DELETE_GAME_ROOM_LOADING = 'DELETE_GAME_ROOM_LOADING';
export const DELETE_GAME_ROOM_SUCCESS = 'DELETE_GAME_ROOM_SUCCESS';
export const DELETE_GAME_ROOM_FAIL = 'DELETE_GAME_ROOM_FAIL';

export const LEAVE_GAME_ROOM_LOADING = 'LEAVE_GAME_ROOM_LOADING';
export const LEAVE_GAME_ROOM_SUCCESS = 'LEAVE_GAME_ROOM_SUCCESS';
export const LEAVE_GAME_ROOM_FAIL = 'LEAVE_GAME_ROOM_FAIL';

export const JOIN_GAME_ROOM_LOADING = 'JOIN_GAME_ROOM_LOADING';
export const JOIN_GAME_ROOM_SUCCESS = 'JOIN_GAME_ROOM_SUCCESS';
export const JOIN_GAME_ROOM_FAIL = 'JOIN_GAME_ROOM_FAIL';

export const ON_GAME_ROOM_USER_STATUS_UPDATE = 'ON_GAME_ROOM_USER_STATUS_UPDATE';

export const END_GAME_ROOM = 'END_GAME_ROOM';
