export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const AUTHENTICATE_SOCKET_LOADING = 'AUTHENTICATE_SOCKET_LOADING';
export const AUTHENTICATE_SOCKET_SUCCESS = 'AUTHENTICATE_SOCKET_SUCCESS';
export const AUTHENTICATE_SOCKET_FAIL = 'AUTHENTICATE_SOCKET_FAIL';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';

export const GET_FEATURE = 'GET_FEATURE';
export const GET_USER = 'GET_USER';

export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

export const ADD_MESSAGE_LOADING = 'ADD_MESSAGE_LOADING';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAIL = 'ADD_MESSAGE_FAIL';

export const DELETE_MESSAGE_LOADING = 'DELETE_MESSAGE_LOADING';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';

export const EDIT_MESSAGE_LOADING = 'EDIT_MESSAGE_LOADING';
export const EDIT_MESSAGE_SUCCESS = 'EDIT_MESSAGE_SUCCESS';
export const EDIT_MESSAGE_FAIL = 'EDIT_MESSAGE_FAIL';
export const CLEAR_MESSAGE_ERROR = 'CLEAR_MESSAGE_ERROR';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_LOBBYS_LOADING = 'GET_LOBBYS_LOADING';
export const GET_LOBBYS_SUCCESS = 'GET_LOBBYS_SUCCESS';
export const GET_LOBBYS_FAIL = 'GET_LOBBYS_FAIL';

export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const JOIN_LOBBY_LOADING = 'JOIN_LOBBY_LOADING';
export const JOIN_LOBBY_SUCCESS = 'JOIN_LOBBY_SUCCESS';
export const JOIN_LOBBY_FAIL = 'JOIN_LOBBY_FAIL';

export const LEAVE_LOBBY_LOADING = 'LEAVE_LOBBY_LOADING';
export const LEAVE_LOBBY_SUCCESS = 'LEAVE_LOBBY_SUCCESS';
export const LEAVE_LOBBY_FAIL = 'LEAVE_LOBBY_FAIL';

export const ASSIGN_LOBBY_ROLE_LOADING = 'ASSIGN_LOBBY_ROLE_LOADING';
export const ASSIGN_LOBBY_ROLE_SUCCESS = 'ASSIGN_LOBBY_ROLE_SUCCESS';
export const ASSIGN_LOBBY_ROLE_FAIL = 'ASSIGN_LOBBY_ROLE_FAIL';

export const START_COBROWSING_SUCCESS = 'PUBLISH_COBROWSING_SUCCESS';
export const START_COBROWSING_FAIL = 'PUBLISH_COBROWSING_FAIL';

export const END_COBROWSING_SUCCESS = 'END_COBROWSING_SUCCESS';
export const END_COBROWSING_FAIL = 'END_COBROWSING_FAIL';

export const UPDATE_COBROWSING_FAIL = 'UPDATE_COBROWSING_FAIL'

export const SUBSCRIBE_COBROWSING_LOADING = 'SUBSCRIBE_COBROWSING_LOADING';
export const SUBSCRIBE_COBROWSING_SUCCESS = 'SUBSCRIBE_COBROWSING_SUCCESS';
export const SUBSCRIBE_COBROWSING_FAIL = 'SUBSCRIBE_COBROWSING_FAIL';

export const UNSUBSCRIBE_COBROWSING_LOADING = 'UNSUBSCRIBE_COBROWSING_LOADING';
export const UNSUBSCRIBE_COBROWSING_SUCCESS = 'UNSUBSCRIBE_COBROWSING_SUCCESS';
export const UNSUBSCRIBE_COBROWSING_FAIL = 'UNSUBSCRIBE_COBROWSING_FAIL';

export const ADD_LOBBY_LOADING = 'ADD_LOBBY_LOADING';
export const ADD_LOBBY_SUCCESS = 'ADD_LOBBY_SUCCESS';
export const ADD_LOBBY_FAIL = 'ADD_LOBBY_FAIL';

export const GET_LOBBY_LOADING = 'GET_LOBBY_LOADING';
export const GET_LOBBY_SUCCESS = 'GET_LOBBY_SUCCESS';
export const GET_LOBBY_FAIL = 'GET_LOBBY_FAIL';

export const EDIT_LOBBY_LOADING = 'EDIT_LOBBY_LOADING';
export const EDIT_LOBBY_SUCCESS = 'EDIT_LOBBY_SUCCESS';
export const EDIT_LOBBY_FAIL = 'EDIT_LOBBY_FAIL';

export const UPDATE_LOBBY_USER_LOADING = 'UPDATE_LOBBY_USER_LOADING';
export const UPDATE_LOBBY_USER_SUCCESS = 'UPDATE_LOBBY_USER_SUCCESS';
export const UPDATE_LOBBY_USER_FAIL = 'UPDATE_LOBBY_USER_FAIL';

export const DELETE_LOBBY_LOADING = 'DELETE_LOBBY_LOADING';
export const DELETE_LOBBY_SUCCESS = 'DELETE_LOBBY_SUCCESS';
export const DELETE_LOBBY_FAIL = 'DELETE_LOBBY_FAIL';

export const RESEED_DATABASE_LOADING = 'RESEED_DATABASE_LOADING';
export const RESEED_DATABASE_SUCCESS = 'RESEED_DATABASE_SUCCESS';
export const RESEED_DATABASE_FAIL = 'RESEED_DATABASE_FAIL';

export const START_VIDEO_CALL_LOADING = 'START_VIDEO_CALL_LOADING';
export const START_VIDEO_CALL_SUCCESS = 'START_VIDEO_CALL_SUCCESS';
export const START_VIDEO_CALL_FAIL = 'START_VIDEO_CALL_FAIL';
export const LEAVE_VIDEO_CALL_SUCCESS = 'LEAVE_VIDEO_CALL_SUCCESS';
export const LEAVE_VIDEO_CALL_FAIL = 'LEAVE_VIDEO_CALL_FAIL';
export const BYPASS_VIDEO_CALL = 'BYPASS_VIDEO_CALL';

export const LOBBY_STATE_UPDATE = 'LOBBY_STATE_UPDATE';
export const VIDEO_STATE_UPDATE = 'VIDEO_STATE_UPDATE';
export const EDITOR_STATE_UPDATE = 'EDITOR_STATE_UPDATE';

export const UPDATE_ONBOARDING_STEP = 'UPDATE_ONBOARDING_STEP';

export const SET_VIDEO_TRACK_ID = 'SET_VIDEO_TRACK_ID';
export const SET_AUDIO_TRACK_ID = 'SET_AUDIO_TRACK_ID';

export const GET_GAMES_LOADING = 'GET_GAMES_LOADING';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL';

export const LOAD_GAME_LOADING = 'LOAD_GAME_LOADING';
export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';
export const LOAD_GAME_FAIL = 'LOAD_GAME_FAIL';

export const ADD_GAME_LOADING = 'ADD_GAME_LOADING';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAIL = 'ADD_GAME_FAIL';

export const EDIT_GAME_LOADING = 'EDIT_GAME_LOADING';
export const EDIT_GAME_SUCCESS = 'EDIT_GAME_SUCCESS';
export const EDIT_GAME_FAIL = 'EDIT_GAME_FAIL';
export const CLEAR_GAME_ERROR = 'CLEAR_GAME_ERROR';

export const UNLOAD_GAME = 'UNLOAD_GAME';
export const EDIT_GAME_MODEL = 'EDIT_GAME_MODEL'
export const SET_GAME_INSTANCE = 'SET_GAME_INSTANCE';

export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';

export const OPEN_LIVE_PHYSICS_EDITOR = 'OPEN_LIVE_PHYSICS_EDITOR';
export const OPEN_LIVE_WORLD_EDITOR = 'OPEN_LIVE_WORLD_EDITOR';
export const OPEN_LIVE_CAMERA_EDITOR = 'OPEN_LIVE_CAMERA_EDITOR';
export const CLOSE_LIVE_EDITOR = 'CLOSE_LIVE_EDITOR';
export const CHANGE_EDITOR_CAMERA_ZOOM = 'CHANGE_EDITOR_CAMERA_ZOOM';

export const SELECT_CLASS = 'SELECT_CLASS';
export const CLEAR_CLASS = 'CLEAR_CLASS';

export const SELECT_BRUSH = 'SELECT_BRUSH';
export const CLEAR_BRUSH = 'CLEAR_BRUSH';

export const ON_SOCKET_CONNECT = 'ON_SOCKET_CONNECT';
export const ON_SOCKET_DISCONNECT = 'ON_SOCKET_DISCONNECT';

export const ON_AUTHENTICATE_SOCKET_SUCCESS = 'ON_AUTHENTICATE_SOCKET_SUCCESS';
export const ON_AUTHENTICATE_SOCKET_FAIL = 'ON_AUTHENTICATE_SOCKET_FAIL';

export const ON_GAME_INSTANCE_UPDATE = 'ON_GAME_INSTANCE_UPDATE';
export const ON_GAME_MODEL_UPDATE = 'ON_GAME_MODEL_UPDATE';

export const ON_LOBBY_UPDATE = 'ON_LOBBY_UPDATE';
export const ON_LOBBY_USER_STATUS_UPDATE = 'ON_LOBBY_USER_STATUS_UPDATE';
export const ON_COBROWSING_UPDATE = 'ON_COBROWSING_UPDATE';
export const ON_COBROWSING_STATUS_UPDATE = 'ON_COBROWSING_STATUS_UPDATE';
export const ON_COBROWSING_SUBSCRIBED = 'ON_COBROWSING_SUBSCRIBED';

export const GET_SPRITESHEET_DATA_LOADING = 'GET_SPRITESHEET_DATA_LOADING'
export const GET_SPRITESHEET_DATA_SUCCESS = 'GET_SPRITESHEET_DATA_SUCCESS'
export const GET_SPRITESHEET_DATA_FAIL = 'GET_SPRITESHEET_DATA_FAIL'

export const CLEAR_EDITOR_FORMS = 'CLEAR_EDITOR_FORMS'
export const CLEAR_EDITOR = 'CLEAR_EDITOR'
export const CLEAR_EDITOR_INSTANCE = 'CLEAR_EDITOR_INSTANCE'

export const TOGGLE_LAYER_VISIBILITY = 'TOGGLE_LAYER_VISIBILITY'
export const TOGGLE_GAME_INSTANCE_PAUSED = 'TOGGLE_GAME_INSTANCE_PAUSED'
export const RESET_GAME_INSTANCE = 'RESET_GAME_INSTANCE'

export const OPEN_CREATE_CLASS_FLOW = 'OPEN_CREATE_CLASS_FLOW'
export const OPEN_CREATE_BRUSH_FLOW = 'OPEN_CREATE_BRUSH_FLOW'
export const CLOSE_CREATE_CLASS_FLOW = 'CLOSE_CREATE_CLASS_FLOW'
export const CLOSE_CREATE_BRUSH_FLOW = 'CLOSE_CREATE_BRUSH_FLOW'
export const UPDATE_CREATE_CLASS = 'UPDATE_CREATE_CLASS'
export const UPDATE_CREATE_BRUSH = 'UPDATE_CREATE_BRUSH'
export const UPDATE_CREATE_CLASS_STEP = 'UPDATE_CREATE_CLASS_STEP'
export const UPDATE_CREATE_BRUSH_STEP = 'UPDATE_CREATE_BRUSH_STEP'

export const UPDATE_BRUSH_SIZE = 'UPDATE_BRUSH_SIZE'

export const LOCK_INTERFACE = 'LOCK_INTERFACE';
export const UNLOCK_INTERFACE = 'UNLOCK_INTERFACE';