export const defaultStep = {
  skippable: false,
  prompts: {},
  clickToType: null,
  clickToData: {},
  requirements: {},
  isAutogenerated: false,
}

// UMM like so all interfaceIds should get like 'how to click' 
// thing and whether or not to open cobrowsing

// yeah like when reaching the step it will turn cobrowsing on or off
// activeCobrowsing

// Open Interface
// Run Effect
// Run Animation Lobby Event

// WHAT ARE THE ROLES IN YOUR EXPERIENCE_MODEL

export const defaultConversationPrompt = {
  role: '',
  text: '',
  gameEvent: '',
  lobbyEvent: '',
}


