export const ACTIVITY_VIEW_MONOLOGUE = 'ACTIVITY_VIEW_MONOLOGUE'
export const ACTIVITY_VIEW_GALLERY = 'ACTIVITY_VIEW_GALLERY'
export const ACTIVITY_VIEW_SPEAKER = 'ACTIVITY_VIEW_SPEAKER'
export const ACTIVITY_VIEW_BROWSE = 'ACTIVITY_VIEW_BROWSE'
export const ACTIVITY_VIEW_CHATROOM = 'ACTIVITY_VIEW_CHATROOM'
export const ACTIVITY_VIEW_PLAY_GAME = 'ACTIVITY_VIEW_PLAY_GAME'
export const ACTIVITY_VIEW_WATCH_GAME = 'ACTIVITY_VIEW_WATCH_GAME'
export const ACTIVITY_VIEW_DRAWING = 'ACTIVITY_VIEW_DRAWING'
export const ACTIVITY_VIEW_TEXT = 'ACTIVITY_VIEW_TEXT'

//Browse, Group, Teams, Pair, Chat