import { ENTITY_MODEL_DID, POWERUP_ENTITY_TYPE_PREFIX } from "../game/constants"

export function getPlayerPowerupEntityId (entityModelId) {
  return ENTITY_MODEL_DID+POWERUP_ENTITY_TYPE_PREFIX+entityModelId
}

export function getAutogeneratedTagDescription({effectName, eventName, targetName}) {
  if(targetName === '-none') {
    return `When the Player ${eventName} event occurs`
  } else if(targetName === '-player') {
    return `When the Player ${eventName} event occurs`
  } else if(targetName === '-entity') {
    return `When the Player ${eventName} event occurs`
  }
}

export function getAutogeneratedTagName({effectName, eventName, targetName}) {
  if(targetName === '-none') {
    return `${effectName}`
  } else if(targetName === '-player') {
    return `${effectName} - Player`
  } else if(targetName === '-entity') {
    return `${effectName} - this`
  }
}
