export const ADMIN_ROLE = 'ADMIN'
export const ON_MY_VIDEO_QUALITY_STATUS_UPDATE = 'ON_MY_VIDEO_QUALITY_STATUS_UPDATE'

export const PHASER_ERROR = 'PHASER_ERROR'
export const GAME_CONNECTION_LOST = 'GAME_CONNECTION_LOST'
export const VIDEO_CONNECTION_LOST = 'VIDEO_CONNECTION_LOST'
export const SOCKET_CONNECTION_LOST = 'SOCKET_CONNECTION_LOST'
export const SERVER_CONNECTION_LOST = 'SERVER_CONNECTION_LOST'
export const INTERNET_SPEED_TEST_FAIL = 'INTERNET_SPEED_TEST_FAIL'
