export const ADMIN_ROLE = 'ADMIN'
export const ON_MY_VIDEO_QUALITY_STATUS_UPDATE = 'ON_MY_VIDEO_QUALITY_STATUS_UPDATE'

export const PHASER_ERROR = 'PHASER_ERROR'
export const GAME_CONNECTION_LOST = 'GAME_CONNECTION_LOST'
export const COBROWSING_CONNECTION_LOST = 'COBROWSING_CONNECTION_LOST'
export const CODRAWING_CONNECTION_LOST = 'CODRAWING_CONNECTION_LOST'

export const SOCKET_CONNECTION_LOST = 'SOCKET_CONNECTION_LOST'
export const INTERNET_SPEED_TEST_FAIL = 'INTERNET_SPEED_TEST_FAIL'


export const LOBBY_USER_PRESENT_DELTA = 15000