export const IMAGE_TYPE_SNAPSHOT = 'IMAGE_TYPE_SNAPSHOT'
export const IMAGE_TYPE_LAYER = 'IMAGE_TYPE_LAYER'
export const IMAGE_TYPE_CANVAS = 'IMAGE_TYPE_CANVAS'
export const IMAGE_TYPE_SPRITE = 'IMAGE_TYPE_SPRITE'

export * from './dallESession'